---
output: 
    thesisdown::thesis_pdf: 
      toc: true
      toc-depth: 2
      latex_engine: pdflatex
editor_options: 
  chunk_output_type: console
---

The best way to make a list of abbreviations is to make a data frame using `R`, make a table of this data frame using `kable` and specifying the format as \LaTeX, then copy and paste the output of that to make the printed table as below

this is a reference: [@freedman2022] and this is a ref [@RN3444]

<!--
```{r, echo=FALSE}
library(tidyverse)
library(kableExtra)

table <- tibble(

  abbreviation = c("CMD",
                   "SMI",
                   "APMS",
                   "ICD-11",
                   "DSM-V",
                   "APE",
                   "AME",
                   "RITB",
                   "STOPSIM",
                   "ADRN",
                   "PSTD",
                   "cPTSD",
                   "GAD",
                   "OCD",
                   "ONS",
                   "AE",
                   "GP",
                   "HPD",
                   "DSM-III",
                   "DSM-IV",
                   "CMHT",
                   "IPS",
                   "NatCen",
                   "UKDS",
                   "ESRC",
                   "EUL",
                   "SRT",
                   "DALY",
                   "PSQ",
                   "ADHD",
                   "ASD",
                   "CoI",
                   "NSF",
                   "DDA",
                   "AOR",
                   "OR",
                   "SAD",
                   "CIS-R",
                   "SCAN",
                   "NHS",
                   "RQ",
                   "JSA",
                   "NEET"
                   ),
  term = c("Common Mental Health Disorders",
           "Severe Mental Illness",
           "Adult Psychiatric Morbidity Survey",
           "International Classification of Diseases, 11th Revision",
           "Diagnostic and Statistical Manual of Mental Disorders, 5th Edition",
           "Average Partial Effects",
           "Average Marginal Effects",
           "Recovery in the Bin",
           "Stop Serenity Integrated Mentoring",
           "Administrative Data Research Network",
          "Post Traumatic Stress Disorder",
          "Complex Post Traumatic Stress Disorder",
           "Generalised Anxiety Disorder",
          "Obsessive Compulsive Disorder",
          "Office for National Statistics",
          "Accident and Emergency",
          "General Practitioner",
          "Histrionic Personality Disorder",
          "Diagnostic and Statistical Manual of Mental Disorders, 3rd Edition",
          "Diagnostic and Statistical Manual of Mental Disorders, 4th Edition",
          "Community Mental Health Teams",
          "Individual Placement and Support",
          "National Centre for Social Research",
          "UK Data Service",
          "Economic and Social Research Council",
          "End User License",
          "Safe Researcher Training",
          "Daily Adjusted Life Years",
          "Psychosis Screening Questionaire",
          "Attention Deficit Hyperactivity Disorder",
          "Austism Spectrum Disorders",
          "Conflicts of Interest",
          "National Service Framework",
          "Disability Discrimination Act",
          "Adjusted Odds Ratio",
          "Odds Ratio",
          "Seasonal Affective Disorder",
          "Clinical Interview Schedule-Revised",
          "Schedules for Clinical Assessment in Neuropsychiatry",
          "National Health Service",
          "Research Question",
          "Job Seekers Allowance",
          "Not in Education, Employment, or Training"
          )) %>%
  arrange(term)  # order alphabetically
table <- unique(table) # remove duplicates

#\newpage

## Step 2 - make a \LaTeX table using `kable` {-}

knitr::kable(table, longtable = T, booktabs = T, format = "latex", escape = F,
             row.names = F,
             col.names = c("Abbreviation","Term")) %>%
  kable_styling(latex_options = c("HOLD_position", "repeat_header"),
                position = "center")
```
-->

\begin{longtable}{ll}
\toprule
Abbreviation & Term\\
\midrule
\endfirsthead
\multicolumn{2}{@{}l}{\textit{(continued)}}\\
\toprule
Abbreviation & Term\\
\midrule
\endhead

\endfoot
\bottomrule
\endlastfoot
A\&E & Accident and Emergency\\
AOR & Adjusted Odds Ratio\\
ADRN & Administrative Data Research Network\\
APMS & Adult Psychiatric Morbidity Survey\\
ADHD & Attention Deficit Hyperactivity Disorder\\
\addlinespace
ASD & Austism Spectrum Disorders\\
AME & Average Marginal Effects\\
APE & Average Partial Effects\\
CIS-R & Clinical Interview Schedule-Revised\\
CMD & Common Mental Health Disorders\\
\addlinespace
CMHT & Community Mental Health Teams\\
cPTSD & Complex Post Traumatic Stress Disorder\\
CoI & Conflicts of Interest\\
DALY & Daily Adjusted Life Years\\
DSM-III & Diagnostic and Statistical Manual of Mental Disorders, 3rd Edition\\
\addlinespace
DSM-IV & Diagnostic and Statistical Manual of Mental Disorders, 4th Edition\\
DSM-V & Diagnostic and Statistical Manual of Mental Disorders, 5th Edition\\
DDA & Disability Discrimination Act\\
ESRC & Economic and Social Research Council\\
EUL & End User License\\
\addlinespace
GP & General Practitioner\\
GAD & Generalised Anxiety Disorder\\
HPD & Histrionic Personality Disorder\\
IPS & Individual Placement and Support\\
ICD-11 & International Classification of Diseases, 11th Revision\\
\addlinespace
JSA & Job Seekers Allowance\\
NatCen & National Centre for Social Research\\
NHS & National Health Service\\
NSF & National Service Framework\\
NEET & Not in Education, Employment, or Training\\
\addlinespace
OCD & Obsessive Compulsive Disorder\\
OR & Odds Ratio\\
ONS & Office for National Statistics\\
PSTD & Post Traumatic Stress Disorder\\
PSQ & Psychosis Screening Questionaire\\
\addlinespace
RITB & Recovery in the Bin\\
RQ & Research Question\\
SRT & Safe Researcher Training\\
SCAN & Schedules for Clinical Assessment in Neuropsychiatry\\
SAD & Seasonal Affective Disorder\\
\addlinespace
SMI & Severe Mental Illness\\
STOPSIM & Stop Serenity Integrated Mentoring\\
UKDS & UK Data Service\\*
\end{longtable}
