---
output: 
    thesisdown::thesis_pdf: 
      toc: true
      toc-depth: 2
      latex_engine: pdflatex
bibliography: bib/thesis.bib
csl: csl/nature.csl
space_betwee_paragraphs: true
fig_caption: true
always_allow_html: yes
link-citations: true
lot: true
lof: true
indent: true
header-includes: # include other LaTeX packages here
    \usepackage{booktabs}
    \usepackage{longtable}
    \usepackage{siunitx}
    \usepackage[left]{lineno}
    \usepackage{float}
    \floatplacement{figure}{H}
    \linenumbers
    \pagestyle{plain}
    \raggedbottom 
    \usepackage{indentfirst}
editor_options: 
  chunk_output_type: console
---

<style>
body {
text-align: justify}
</style>

**Background:** Severe mental illness and its relationship to employment has been a growing area of interest in recent years. Individuals living with a severe mental illness, such as those with disorders like psychosis and personality disorders, often face significant barriers in obtaining and maintaining employment. However, employment can provide not only financial benefits, but also social and psychological benefits that can be restorative for individuals living with severe mental illness. The aim was to examine the rates and factors associated with employment among individuals living with severe mental illness and common mental health disorders, as well as the barriers or enablers, such as socioeconomic status, ethnicity, education, physical health, involvement in services that are experienced by this population, and provide a deeper understanding of the experiences and challenges faced by individuals living with severe mental illness and common mental health disorders in the workforce.

**Methods:** A retrospective population-based observational study using survey data was employed. All individuals between 16 and 75 years old and living in England during time the Adult Psychiatric Morbidity Survey (APMS) was conducted in the years 2000 and 2007 were included. A measurement of economic activity was derived from several International Labour Organization (ILO) based questions asking individuals about work. Logistic regression models reporting Average Partial Effects (APEs) were employed to investigate associations between dependant and independent variables. Severe mental illness (SMI) and common mental health disorders and their presence was derived from several clinically validated measures included and conducted during the course of the APMS survey waves. Supplementing this quantitative stance is the inclusion of an argument for wider adoption and inclusion of reflexive practice in quantitative research, and accompanied by three short reflexive pieces that show this in practice (titled ‘Beginning’, ‘Middle’ and ‘End’). 

**Results:** The APMS study included 7,247 participants in the 2000 survey wave and 6,453 participants in the 2007 survey wave. 70% of all individuals were economically active in the year 2000 and 69% in the year 2007. 17% of individuals had a common mental health disorder (CMD) in both survey years. In the year 2000, 0.8% of individuals lived with a severe mental illness (SMI), and 0.7% in the year 2007.  Having an SMI or CMD was associated with being economically inactive. Demographic and other factors, such as age, gender, education, ethnicity, physical health, social class, treatment, and service use were all associated with worse outcomes for those living with an SMI or CMD. 

**Conclusion:** This work aimed to investigate the relationship between common mental disorders, severe mental illness, and economic activity in England. It provides a detailed understanding of the patterns of economic activity among individuals with common mental health disorders severe mental illness and how these vary by both individual and local labour market characteristics. This contributes to a better understanding of the complexity of the relationship between common mental health disorders, severe mental illness and economic activity, and the importance of considering other factors that may interact with these conditions in determining employment outcomes. This has important implications for policymakers, healthcare providers, and individuals living with common mental health disorders and severe mental illness as it also provides a platform for further research and development of policies and interventions that aim to support and empower individuals living with these conditions to improve their employment outcomes.

**[Word Count: 72, 710]**
