---
output:
    thesisdown::thesis_pdf: default
bibliography: bib/thesis.bib
csl: csl/harvard.csl
space_betwee_paragraphs: true
fig_caption: true
always_allow_html: yes
link-citations: true
toc-depth: 3
lot: true
lof: true
editor_options: 
  chunk_output_type: console
---

# Literature Review {#chapter2}

## Chapter Overview

The aim of this chapter is to scope out the literature relevant to the main themes of this thesis outlined in the introduction and identify where links can be made. This chapter summarises academic and policy literature relevant to the main project themes. As the main project pivoted to use English data, there was a focus on the structures and policies in this country. However, this is placed in the wider context of the UK as well as considering views from the global south. 

The chapter is organised in five parts, each building upon the previous to provide a comprehensive understanding of the relationship between severe mental illness and employment outcomes in the UK.

In Section 2.2, we begin by defining the most commonly used terms in the literature on severe mental illness and employment, providing a foundation for the rest of the chapter.

Moving on to Section 2.3, we delve into the importance of understanding severe mental illness in the context of UK services and the broader social background. We provide an overview of academic literature and policy regarding severe mental illness and its measurement, definition, and impact.

In Section 2.4, we focus on the specific topic of employment outcomes for individuals living with severe mental illness. We examine what it means to be economically active or inactive with severe mental illness, how this is treated and viewed by services, and the perceived impact on severe mental illness.

Section 2.5 delves into the policies in place regarding severe mental illness and employment, providing historical context and reviewing empirical evidence on the nature of the interaction between severe mental illness and employment outcomes.

Finally, in Section 2.6, we discuss the use of administrative data for research in relation to severe mental illness. We explore what access to administrative data involves, the benefits and drawbacks of using this type of data, and outline the data sources selected for this project, along with the justification for their inclusion.

Given the nature of this review, the search strategy for literature employed differing methods. The first section on severe mental illness used traditional bibliographic database searches (Web of Science, Google Scholar) for key terms: “severe mental illness” and variations within, including individual conditions: “schizophrenia”, “psychosis”, “PTSD”, “BPD”, and “employment” and its variations: “unemployment”, “economically in/active”. As an overview of the whole topic and subsections was sought, initial searches included only systematic reviews and, where necessary, references from citation lists were retrieved and included.

“Grey” literature was also searched for using websites of prominent charities (e.g. Mind, think-tanks (e.g. the Centre for Mental Health), research groups (e.g. the Centre for Global Mental Health), and prominent grass-root, activist-led and lived experience groups (e.g. Time & Space Glasgow, Recovery in the Bin, Stop SIM, Deaths by Welfare). Literature on lived experiences of severe mental illness and navigating employment was mostly found from these “grey” sources with a “snowball” method from reference lists employed to identify further reading. In addition, relevant publications from UK governments and health and support services on their policies were sought, alongside critiques from traditional and grass-roots literature. 

Background information on administrative data was informed by reports produced by the Administrative Data Research Network (ADRN) and references contained within.

An initial review and searches of literature were conducted in Winter 2017 with continual updates in Spring 2018, 2019, and then in line with the project being reorientated due to COVID-19 in Spring 2020. A formal update of this review was completed in Autumn 2022. The review provides a summary after each section with a synthesis of sections contained in the
chapter conclusion.

## Definitions

This section covers the different ways severe mental illness, common mental health disorders, and employment have been defined in the literature, both in the UK and internationally. There is no accepted consensus for terms around severe mental illness in particular, either nationally or internationally, so based on the most up to date literature a consensus is reached on these definitions. The definitions here are the definitions which will be used throughout, but section 2.3.2 discusses in more critical terms how the term is more contested and subject to varying definitions. 

### Severe Mental Illness 

The term severe mental illness is defined as a mental, behavioural, or emotional disorder that leads to serious functional impairment, and substantially interferes with daily life [@RN4721]. Severe mental illness includes schizophrenia, psychosis disorders, personality disorders, eating disorders, and post-traumatic stress disorder (PTSD) and complex post-traumatic stress disorder (CPSTD) [@RN4722] among others. These illnesses are associated with an increase in all-cause mortality, leading to a life expectancy reduction of up to 20% [@RN4723]. This is due in part to the high prevalence of physical comorbidities among those with severe mental illness in comparison to the general population, including cardiovascular, metabolic, infectious, and respiratory conditions [@RN2272]. Those living with severe mental illness are also more likely to be impacted by psychosocial stressors, such as loneliness [@RN2273]. All severe mental illness conditions by ICD-11 codes can be viewed in Appendix A.

### Common Mental Disorders 

The term common mental disorders refer to a set of illnesses that are much more common in the general population. They can cause marked emotional distress and can interfere with daily function, but do not usually affect insight or cognition [@RN2238]. Common mental disorders comprise depressive and anxiety disorders and are a leading cause of disability worldwide [@RN2276]. Depressive disorders include mild, moderate, and severe depressive disorders and dysthymia (a milder but more persistent form of depression), while anxiety disorders include generalised anxiety disorder (GAD), panic disorder, phobias, social anxiety disorder, and obsessive-compulsive disorder (OCD). The WHO estimate 5.0% of adults globally suffer with depression, with as many affected by anxiety disorders [@RN2274]. 

### Economic Activity and Employment Status

This project applied the definition set out by the Office for National Statistics (ONS) for the terms ‘economically inactive’, or ‘economic inactivity’. The term includes individuals “aged 16 and over without a job who have not sought work in the last four weeks and/or are not available to start work in the next two weeks” [@RN1111]. Working-age (16 – 64) economically inactive individuals comprise a diverse range of groups. Students tend to be young and at the start of their working lives. Most individuals looking after the family and the home still tend to be female and of child-rearing age, and retirees tend to be close to retirement age. A small number of individuals also fall under what is called *“discouraged workers”*. They are not trying to find work because they believe there is not any available, and it is possible that it would be relatively easy to convince these people to re-enter the labour force [@RN4724]. Whereas for other groups, like full-time students or carers, or those with illnesses, the practical barriers to work may be much higher, even if they do want a job. This project also applied the ONS definition for the term ‘economically active’, that encompasses individuals aged sixteen and over who are either in employment or unemployed. Those in employment are defined as individuals aged 16 and over who are employees paid a wage by an employer for the work that they do, and they can be permanent and temporary employees. Self-employed describes individuals who in their main employment work on their own account, whether or not they have employees. Individuals in employment can also be unpaid family workers - those who work in a family business and who do not receive a formal wage or salary but benefit from the profits of that business – they are also distinct from unpaid family carers, who are not included in employment definitions. This definition also includes individuals on government-supported training programmes, who are classified as being employed only if they are engaging in any form of work, work experience or work-related training; if they are not engaging in such activities they are classified as unemployed or economically inactive [@RN1111]. Individuals in the unemployed group are defined as those who are currently without a job but who either have been actively seeking work in the past four weeks and are available to start work in the next two weeks, or have found a job and are waiting to start it in the next two weeks. 

### Severe Mental Illness

This section reviews relevant literature regarding severe mental illness in the UK. Firstly, an overview of the main context is provided, the scale and composition of the population with severe mental illness in the UK, before more in-depth reviews of three main themes arising from this: concepts of severe mental illness, measuring severe mental illness, and finally the impact of severe mental illness on employment outcomes.

### Context

People with severe mental illness are among the most disadvantaged in society, and many experience social and economic hardship as a direct result of the illness. For example, reviews show much lower rates of being employed compared to the general community, higher rates of being homeless, and lower rates of social and romantic relationships [@RN3444]. The context of serious mental illness in the United Kingdom is one that is characterized by a range of demographic variations. In terms of distribution, severe mental illness is known to affect individuals of all ages and genders, with certain populations being at a higher risk of developing the condition
In terms of age, severe mental illness is known to occur most frequently in individuals between the ages of 25 and 44. This is particularly true for conditions such as schizophrenia, bipolar disorder, and major depressive disorder. However, it is also important to note that severe mental illness can occur at any age, with children and older adults also being at risk [@RN4726].

In terms of gender, research suggests that severe mental illness affects men and women differently. For example, women are more likely to be diagnosed with depression and anxiety disorders, while men are more likely to be diagnosed with schizophrenia and substance use disorders. However, it is important to note that these differences may be influenced by factors such as societal expectations, access to healthcare, and help-seeking behaviours.

In terms of socioeconomic status, individuals from lower income groups and ethnic minorities are at a higher risk of developing severe mental illness. This may be due to a range of factors, including poverty, lack of access to healthcare, and discrimination.

It is important to note that the distribution of severe mental illness in the UK is complex and multifaceted. Factors such as age, gender, and socioeconomic status all play a role in determining an individual's risk of developing severe mental illness. It is important that research and interventions take these demographic variations into account to effectively address the needs of individuals living with severe mental illness.

In addition to living and coping with the illness, people with severe mental illness must also cope with the misguided beliefs, stereotypes and prejudice that result from misconceptions about mental illness in society. Common misconceptions held by the general population as well as health, social and academic systems include: that they are dangerous, violent or behave unpredictably [@RN4727]; that they are incompetent and cannot look after themselves [@RN4728]; that they should be avoided socially, romantically, or professionally and that their illness is a life sentence with little or no chance of recovery [@RN4730].

People with schizophrenia and borderline personality disorder report particularly high rates of discrimination from their communities, which undermines recovery – whatever recovery means to them. Data from twenty-seven countries globally [@RN4732] shows that nearly half of individuals with severe mental illness report being treated unfairly by friends and family. Harangozo and colleagues recent review of stigma towards their family members living with schizophrenia found similar levels [@RN4732]. A significant proportion of individuals reported discrimination in finding or keeping a job (29%). Such discrimination has been further evidenced in several recent qualitative studies. One by Juurlink and colleagues into employment discrimination of individuals with borderline personality disorder, found a high number of medical professionals reinforcing employers’ beliefs that employees with BPD could be ‘bad’ employees [@RN2254]. Work by Hampson and colleagues found high rates of discrimination upon disclosure at interview, being treated differently by colleagues, less tolerance to mistakes being shown by managers, and high rates of victimisation and less support for sick leave while in employment [@RN3487]. Feminist researchers call for action to rename conditions such as BPD or schizophrenia and to abolish the framework that supports these diagnoses, asserting that BPD in particular medicalises women’s emotions, trauma reactions, and behaviours in a neoliberal society. In comparison, men showing similar symptoms are more often diagnosed with schizophrenia [@RN2369]. Others assert that this critical approach to these labels’ risks invalidating the individuals who experience physical and mental distress that would be labelled as BPD [@RN2235].

The findings that 39% of individuals with severe mental illness feel disrespected by mental health staff, particularly those with BPD, is deeply concerning. This suggests that there is a widespread issue of discrimination and prejudice within the mental health field, which has serious implications for the well-being and treatment of individuals with BPD and severe mental illness. Furthermore, the fact that mental health professionals consistently rated individuals with BPD as *“ineffective”*, *“incomprehensible”*, *“dangerous”*, *“unworthy”*, *“immoral”*, *“undesirable to be with [romantically, professionally or socially]”*, and dissimilar to the general population, highlights a lack of understanding and empathy among mental health professionals towards individuals with BPD. This further compounded by the fact that similar views are held by potential employers, suggesting that discrimination and prejudice towards individuals with BPD and severe mental illness extends beyond the mental health field.

The methods used in the studies by Papathanasiou and Stylianidis and Juurlink and colleges should also be evaluated from a social justice lens. It is important to consider the potential biases and limitations of the methods used, and how these may have affected the findings. Additionally, it is important to consider how the representation of individuals with BPD and severe mental illness in the studies may have been influenced by the methods used. For example, if the studies primarily recruited participants from a specific demographic or location, the findings may not be generalizable to other populations [@RN2319; @RN2254].

The work of grass roots, lived experience groups such as Recovery in the Bin, highlights the importance of listening to the voices and experiences of individuals with BPD and severe mental illness, in order to challenge the negative stereotypes and discrimination they face. The co-production of research by these groups is a crucial step towards creating a more just and equitable society for individuals with BPD and severe mental illness. Overall, findings highlight the deeply ingrained negative attitudes towards individuals with severe mental illness, particularly those with BPD, among mental health professionals and potential employers. This is a clear indication of the systemic discrimination and stigmatization faced by individuals with severe mental illness in society. The fact that these attitudes are prevalent among professionals who are responsible for providing care and support for individuals with severe mental illness, is particularly concerning as it suggests that these individuals may not be receiving the appropriate level of care and support.

While this prevalent negative view of severe mental illness is one of the justifications for the research carried out for this thesis, the remainder of this section will expand on the themes outlined above. Firstly, an overview of literature regarding the complexity of the concept and definition of severe mental illness is presented. This is followed by a review of the methods that have been employed to measure severe mental illness. Finally, an overview of relevant literature regarding health, social and employment inequalities in the context of severe mental illness is also presented with a specific focus on UK based literature.

### Concepts

The concept of severe mental illness lacks a consensual definition and is a combination of several different conditions that are in themselves, contested and hard to operationalise. Each condition represented within the severe mental illness umbrella only conceptualises a small percentage of what “living with severe mental illness” means to that individual, and the experience of any one of these conditions is not homogeneous either [@RN2321]. For example, the condition schizophrenia is considered to only cover around 30% of poor outcomes in individuals with severe mental illness yet has paradoxically become the dominant lens through which everything “psychotic” is observed, even though schizophrenia itself sits within a much broader conceptualisation of psychosis [@RN2326]. Psychosis itself can also be considered its own condition as well as a symptom of other severe mental illness conditions. The inability of psychiatry to consider psychosis, or any other condition within the severe mental illness umbrella, as a multidimensional response to individual experiences hampers further research and recovery-oriented practice [@RN2328]. 

Ever since their conception, severe mental illness and the conditions within have been an *“essentially contested concept”* [@RN3494]. For example, the symptomatology for schizophrenia has changed little since its inception in 1893 by Kraepelin as *“dementia praecox”* [@RN3497]. For decades, biological approaches have been tested in an attempt to reverse-engineer the hypothesized disease entity of severe mental illness. However, despite claims of the existence of genes for schizophrenia or chemical imbalances, the biological findings in psychiatry, whilst fascinating, are unreliable [@RN3494]. Discussion about severe mental illness and distress are dominated by the biomedical model. This speaks to the success of the biomedical model in dominating academic and mainstream understanding of severe mental illness. Many scholars, especially from grass roots and lived experience groups underscore the importance of this language in challenging the biomedical model of mental illness [@RN2337]. 

The biomedical model’s approach to understanding the mind as distinct from the body, or the mind/body dichotomy is also key to understanding the concept of severe mental illness as it defines the Western position of mental illness as a phenomenon distinct from physical illness [@RN3499]. This dualism is normalised and exported outside of the Western medical model to other countries. However holistic understandings do not separate the mind from the body or the person from the environment [@RN3500]. Pilling’s work [@RN4734] which drew on interviews with participants around their understandings cements this idea that these concepts, although helpful for some [RN3434], can also be harmful and lead to a sense of helplessness in having others, including medical professionals, define subjective experiences in this way:

> *“Oh, mentally ill. Oh, well, I hate that
> one. Because that just says that some
> people are healthy, and some people are
> ill and I’m one of the ill people. And
> mental health is separate from physical
> health and it’s, you know, I have mental > problems. Yeah, so that one does not sit > well with me. It sounds like something
> that a doctor would call a patient in a
> not-helpful way.”* (Jared in Pilling,
> 2022, p. 67)

This changing understanding of severe mental illness as a reaction to distress experienced by many people in everyday life challenges a fundamental characteristic of the biomedical model: the categorising of people as either sane or *"mad"*. A critique of the distinction between mad and sane and the pathologising of those put in the category is common among scholars seeking other ways to conceptualise severe mental illness. For example, within the field of Mad Studies, research argues that the ‘us’ and ‘them’ distinction has had a number of serious negative consequences for those living with severe mental illness, including the suppression of their lived experience, and forced medical treatment [@RN2334]. According to Bentall and Pilling [@RN4734], evidence shows that using these binary ways of conceptualising experience leads to distress in of itself, as well as leading to dehumanisation and marginalisation, with Bentall [@RN2334] summarising: 

> *“We are mad to varying degrees, that the > boundaries of madness are subject to
> negotiation, and that some of us get on
> very well despite being [in psychiatric
> terms] quite psychotic for much of the
> time”* (Bentall, 2003, p. 85).

The quote by Bentall highlights the complex and nuanced nature of mental illness, suggesting that the boundaries of madness are not fixed, but rather subject to negotiation. It also implies that individuals with mental illness can lead successful and functional lives, despite being considered *"psychotic"* by psychiatric standards. This perspective challenges the dominant narrative that reduces individuals with mental illness to their diagnosis, and ignores the entirety of their being and accomplishments. It highlights the importance of recognizing the individuality and complexity of those living with mental illness, rather than reducing them to a single label or diagnosis. 

### Measurement 

Measuring the prevalence of severe mental illness can be difficult due to conceptualisation issues, but also due to the nature of the conditions within severe mental illness. Onset can happen suddenly, and individuals may present at a number of places, including local accident and emergency department (A\&E), general practitioner (GP) surgeries, self-referral to low-intensity mental health teams, third-party mental health partners, or not present at all until after initial symptoms have subsided. All of these points of contact can result in different treatment routes and data appearing in a number of different datasets under a number of different codes. Measurement and capture at the three different stages of psychosis vary widely, with the capture of the initial prodromal phase often poorly measured due to a relatively long build-up and misunderstanding among generalist primary care staff [@RN4735].

One issue that calls into question how we measure severe mental illness is the validity and reliability of psychiatric labels and the language used to quantify these subjective experiences. Boyle in 2011 (p. 32) writes that *“linguistic devices”* are crucial in grounding social context, because using language is:

> “... the quickest way of implying lack of > intelligibility and suggesting a
> pathological or deficient individual."*
> [@RN3503]

Boyle is referring to the language of psychiatric labels used by mental health practitioners and researchers and acknowledges that dispensing with the medical language that dominates everyday distress would be difficult. Pilling [@RN4734] notes that it can be even more difficult for those who are medicalised and part of a power imbalance to insist on an alternative language in psychiatric settings. Yet Pilling’s work found that participants indicated a resistance to the biomedical terminology of psychiatric labels and ways of understanding [@RN4734]. It is, therefore, important to explore the implications that arise when biomedical model language is challenged. As Beresford notes:

> *“the interest of mental health service
> users in exploring different conceptual
> frameworks and approaches has become
> visible through their development of a
> different language, which replaces the
> idea of ‘mental illness’ with terms like > ‘madness’ and ‘mental distress’”.*
> [@RN3498]

The term *"survivor"*, Beresford argues, is a more empowering and accurate term to describe individuals who have experienced mental health issues. Beresford and others have highlighted that the term *"patient"* implies passivity and a lack of agency, whereas *"survivor"* emphasises the resilience and strength of individuals who have navigated the mental health system. There is a growing body of literature on the use of the term *"survivor"* in the context of mental health, which has helped to shift the dominant narrative away from one that portrays individuals with mental health issues as helpless and dependent, towards one that recognizes their agency and ability to overcome adversity.

The ways in which participants in Pilling’s work discussed these matters indicated that language use in formation of identity when living with severe mental illness are complex and sometimes contradictory [@RN4734]. For example, even participants who spoke about rejecting medicalised ways of understanding themselves and their mental health, often used diagnostic labels to make parts of their experience comprehensible, which typifies the difficulty of untangling mental distress from medicalised language. In some cases, this is due to the permeation of psychiatric labels into everyday language, especially labels such as *“depression”* and *“anxiety”* [@RN3505]. However psychiatric labels can also provide a quick way of making sense of particular experiences that do not have other readily available names, even when participants questioned the legitimacy of such labels [@RN4734]. This is indicative of the ways in which ideals that can be theorised as discrete are not necessarily experienced as such, and that identifying with such is not a static process, but one that shifts over time [@RN4734; @RN3505]. 

These mixed feelings about psychiatric labels stem from the critique of the biomedical model and the challenges to the scientific validity of psychiatric labels as a categorisation system. Those, especially within the Mad Studies and lived experience fields claim that the evidence overwhelmingly supports that mental distress, and especially severe mental illness, is an understandable response to structural oppression, trauma, and adverse life experiences [@RN4736; @RN4716; @RN2334], or at least shares space with the chemical imbalance and genetic predisposition theories. Some have also pointed to the increased pathologising of everyday behaviours, emotions, and experiences of distress, such as the recent inclusion of *"prolonged grief disorder"* in the ICD-11 which has seen increasing use during COVID-19, something that has made some clinicians and researchers uncomfortable [@RN2340]. There is also the critique that points to the Mad Studies scholars have also pointed to the gendered, classist, and racist character of psychiatric labels [@RN2341]. 

Mad Studies, a growing interdisciplinary field of study, has brought attention to the ways in which psychiatric labels are not neutral, but are instead shaped by societal power dynamics. Scholars within Mad Studies, such as Beresford and Antic, have highlighted the gendered, classist, and racist character of psychiatric labels. Beresford, for example, has emphasized the importance of normalizing the term *"survivor"* as opposed to terms such as *"patient"* or *"consumer"* which perpetuate negative stereotypes and reinforce oppressive societal structures. Other Mad Studies scholars, such as Cooper and Chrisman, have also shown how psychiatric labels are used to marginalize and oppress already marginalized groups, such as people of colour and those living in poverty [@antic2022decolonizing; @RN2337]

In particular, Antic, in his work *"Decolonizing Madness"*, has highlighted how psychiatric labels and practices have been used as a tool of colonialism and continue to perpetuate the oppression of colonized peoples. He argues that the dominant Western understanding of mental health is inherently Eurocentric and that alternative understandings and practices must be considered in order to truly decolonize mental health. Similarly, Redikopp has explored the intersection of race and psychiatry in her work, showing how Black people have been disproportionately diagnosed and treated for mental illness within the spatiality [@redikopp2021out]. She argues that this is due to the ways in which Blackness is pathologised within the medical and psychiatric fields and the ways in which Black people's experiences of mental distress are not understood or validated within these fields. Together, the work of these scholars, along with others in Mad Studiesdemonstrate the importance of considering the ways in which systems of power and oppression shape and are perpetuated through psychiatric labels and practices, and contributed to a growing body of literature that challenges dominant narratives about mental health and highlights the ways in which psychiatric labels are deeply intertwined with systems of power and oppression [@RN4738; @redikopp2021out]. 

It is also important to note that those who dispute the medicalisation of their experiences, or the reliability of their psychiatric label can be seen to be lacking *“insight”*. Showing a lack of insight is sometimes seen by health care practitioners as a cornerstone of severe mental illness, especially the psychosis conditions [@guidry2019ethical; guidry2019clarifying]. It can then be unsafe to disagree with the psychiatric label given, as this is then seen as a sign of illness and can lead to further medicalisation and coercive treatment [@RN4737]. This is especially the case for those who are marginalized by racism, classism, homophobia, and other kinds of oppression [@RN4734]. Further, a diagnosis is often required for receiving accommodations in the workplace and in education, as well as for more success in navigating the benefits system [@RN3510]. This can create a necessity to acquire a diagnosis even if it is not desired or experienced as otherwise unhelpful [@RN3502; @RN3511].

### Severe Mental Illness and Inequality

The biomedical model assumes that in order for social phenomena, such as severe mental illness, to be *“real”*, they must be based in biology – for example, the gene or chemical imbalance theory -  despite the fact that many of the social constructs that surround lives like time and money are clearly real and have significant impact outwith of these theories [@RN2349]. The ways in which people understand mental illness change according to culture and across social contexts, and these shifting social constructs are not biological. Yet, severe mental illness is real, and society is organized around these concepts in a way that produces material consequences [@RN2348]. As Ang and colleagues in their 2022 work argues, the chemical imbalance theory and biomedical model often results in assumptions that for distress and suffering to be taken ‘seriously’, it needs to have a biological basis for treatment, which is a dangerous assumption. Many people draw attention to the ways in which structural oppression and their life experiences have played a direct role in their mental distress [@RN3549; @RN3518]. This is in contradiction to the biomedical model, which places distress in the individual, attributing the cause to biology, such as chemical imbalances, rather than considering the social constructs and life experiences that can contribute to distress and behaviours that get labelled as symptomatic of mental illness [@RN4734]. Johnson in their 2021 argues that the individualisation of distress pushed by the biomedical model silences those labelled *“mad”* and also fails to account for the structures and dynamics that can lead to experiences of severe mental illness in a capitalist, neoliberal society [@RN2235].

Evidence connects economic inequality and poor mental health [@RN4739]. With experience of socioeconomic disadvantage, including unemployment, low income, precarious employment, poverty, and poor housing consistently associated with poorer mental health outcomes [@RN122]. The work by Ralston and Formby in 2020 found that there has been a significant shift in the occupational position of young people in the UK, particularly in the wake of the Great Recession. Their findings suggested that there had been a reduction in regional inequality in the level of jobs young men and women are doing, with young men experiencing a disproportionate loss of less advantaged occupations and young women experiencing a disproportionate loss of more advantaged occupations [@RN4822]. This shift in occupational position has important implications for mental health outcomes, as research has consistently shown that socioeconomic disadvantage, including unemployment and low income, is associated with poorer mental health outcomes. Thus, the changes in occupational position for young people in the UK may be contributing to increased mental health disparities and inequality [@RN122]. 

Severe mental illness and common mental health disorders are particularly prominent in already marginalized groups who experience social exclusion, shame, discrimination, and trauma, which in turn leads to compound vulnerability – which is when systemic or institutional conditions intersect to create additional barriers in overcoming distress [@RN2358]. For example, significant relationships have been found between higher income inequality and low levels of access to green space and higher incidence rates of severe mental illness conditions like schizophrenia – the *"urbanicity-psychosis"* association [@RN2356; @RN2357]. With Grandison and colleagues [@RN3523] work further supporting the vulnerability link between socioeconomic status, childhood trauma and employment status and increased risk of suicidal behaviour. 

Pickett and Wilkinson's 2010 work has provided evidence linking economic inequality to poor mental health outcomes. Their research found that in more equal societies, individuals have better mental health outcomes compared to those in more unequal societies. This is thought to be due to the fact that in more equal societies, there is less social stratification and fewer status differences, which leads to less social comparison and a greater sense of community. Additionally, in more equal societies, there is less stress and emotional or general insecurity associated with economic insecurity, which is a known risk factor for mental health issues. Overall, Pickett and Wilkinson's work highlights the important relationship between economic inequality and mental health, and underscores the need for addressing economic inequality as a key strategy for improving mental health outcomes.

Shame, both internal and external is central to many forms of emotional distress, especially in those experiencing inequality and severe mental illness or common mental health disorders. It is associated with developing depression and anxiety and disconnect from the community and support networks [@RN3525]. Prolonged humiliation and shame following trauma have been shown to more than double the chances of developing clinical depression and cPTSD [@RN3526]. Therefore those, particularly at risk, are those whose changes in circumstances place them in poverty, such as through job loss [@RN2349]. Fear and distrust also play a part in vulnerability and particularly in severe mental illness and often occurs when a person feels in danger either physically or emotionally [@RN3527]. 

Blaming individuals for their relegation and situation while promoting the idea that those who receive help from a system – be it medical, particularly mental health, or welfare or social systems - are untrustworthy, directly promotes societal distrust of this group, for example the mistrust of those seeking treatment for BPD, or benefits claimants as *“time wasters”*, [@RN2319; @RN3511] while also fostering distrust in these individuals through poor funding of their communities which could be deprived [@RN3527]. Additionally, research has also shown that individuals living in poverty are more likely to experience discrimination and stigmatization, which can lead to poor mental health outcomes [@RN4740]. Overall, the evidence suggests that societal systems and structures that promote inequality and marginalization, including poor funding of marginalized communities and stigmatization of individuals seeking help, contribute to poor mental health outcomes.

Research has also shown that less trusting societies are less equal socially and have subsequent higher rates of mental health issues [@RN4739]. Low levels of individual trust can also increase the chances of a depression diagnosis by half. While those that live in neighbourhoods with elevated levels of distrust and deprivation have an increased risk of poor mental health [@RN2363]. 

A facet of inequality linked to living with severe mental illness is the link between severe mental illness and poor physical health. Research by Seeman still finds that statistic that those diagnosed with schizophrenia die on average, twenty years earlier than the general population [@RN3529]. Around 80% of these deaths are related to *“natural causes”* such as cardiac issues, and the remaining percent attributed to suicide or violence against the individual – those living with severe mental illness are more likely to be murdered than commit murder as is often portrayed in the press [@RN3530]. Likely conditions that contribute to early death are cardiovascular disease, including coronary heart disease, vascular disease, and stroke [@RN3529]; metabolic disease, such as complications from diabetes [@RN99]; respiratory disorders, some cancers and infectious diseases, such as HIV, and Hepatitis C have all been linked with severe mental illness. Other physical health complaints while not life-threatening, but still effect everyday life as well as social and professional relationships can include sexual dysfunction, incontinence and dental and oral hygiene complaints [RN2306]. These can all be extremely personally distressing and socially isolating. While much of this burden can be attributed to the nature of severe mental illness as well as side effects of the treatments, burden also undoubtedly occurs due to the sometimes-unsatisfactory organisation of the health services, attitudes within the medical profession, and societal stigma attached to individuals living with severe mental illness. Those living with psychosis are two to three times more likely to develop the sub-diabetes mellitus than the general population, yet the condition often goes unrecognised by their primary care team for years [@RN3531]. Another study by Manu and colleagues in 2015 found that individuals with schizophrenia and no history of diabetes when screened, 10% were subsequently diagnosed with type 2 diabetes and a further 38% were at elevated risk of developing it [@RN149]. 

This highlights that physical health complaints, while not life-threatening, can still greatly impact an individual's quality of life and can be socially isolating. Additionally, it suggests that the burden of these health issues is not only due to the nature of severe mental illness and side effects of treatment, but also due to the sometimes-unsatisfactory organization of health services, attitudes within the medical profession, and societal stigma attached to individuals living with severe mental illness. Furthermore, individuals with severe mental illness are more likely to develop diabetes and are often not diagnosed by their primary care team for years, and when screened, a significant percentage are at high risk of developing it. This implies that there is a lack of attention and insufficient screening for physical health issues among those living with severe mental illness, which may be a result of societal stigma and negative attitudes towards these individuals.

Within Scotland, a review of 314 general practices compared the extent and type of physical health comorbidities in a sample of 9,677 patients with psychosis and schizophrenia to 1,414,701 controls [@RN102]. They found that patients with psychosis and schizophrenia were more likely to experience comorbid physical conditions, especially hepatitis, constipation, and Parkinson’s disease, than their controls, but that recognition and treatment of these physical health complaints were delayed leading to move severe symptoms before treatment. 

Medication to treat some severe mental illness, also known as an antipsychotic medication, could also cause several metabolic abnormalities. Weight gain, diabetes [@RN143], or neurological disorders, for example, acute tardive dyskinesia and cardio abnormalities [@RN144] have all been recorded. Obesity prevalence within individuals with psychosis has increased in recent years in comparison with the general population, which in itself has also seen a dramatic increase in obesity incidence [@RN2634]. There are a few diseases-specific factors that may cause this propensity in individuals with psychosis, such as increased genetic susceptibility. However, the one factor most likely to cause this weight gain is the use of antipsychotics [@RN147; @RN146]. Recognising the effects of these obesogenic drugs is important as the subsequent weight gain can cause a number of physical health problems, including insulin resistance [@RN150], dyslipidaemia [@RN151], and hypertension [@RN149]. The true impact of antipsychotics on weight gain may have been underestimated due to the lack of comprehensive critical evaluation specifically in the diagnosed population never before exposed to antipsychotics. Many trials only employed short follow up times with the older, long-term diagnosed psychosis population, many of whom had previously been exposed to antipsychotic use during their ‘heyday’ [RN2328]. Qualitative work by Morant and colleagues [@RN2397] highlighted users views on taking antipsychotics, which backed the other studies in having negative effects outwith of the mental health diagnosis:

> *“I’ve developed social phobia, I’ve
> developed diabetes, I’ve got blood
> pressure, I ain’t got many friends...it
> [medication] just ruins your life...it
> makes me lazy. It makes me groggy, first > week it’s just like your body’s hurting, > you’ve got no motivation, makes you lazy > ... It’s just the pain in the body. If
> you go to the gym the next day, it’s
> double the pain, your legs are hurting
> from the medicine...The medicine hammers > you more than the spirits in my life”*
> (Int12 in Morant et al, 2018, p. 3)

## Severe Mental Illness and Employment Outcomes 

This section reviews relevant literature regarding employment outcomes and severe mental illness with a focus on the UK. An overview of the main context is provided before more in-depth reviews of the main themes arising from this: concepts of economic (in)activity and the encroachment of psychiatry on the world of work, and the impact (un)employment can have on an individual’s mental health.

### Context

Increasing employment levels by moving individuals into work, either supportively or punitively, and reducing social security spending has been a key policy concern for some time in the UK [@RN2296], alongside the view that participation in employment is a route out of poverty, as well as an effective way to improve health [@RN2298]. Within public policy and health circles, there have been heated debates over the question *"is work good for health?"* [@RN175], with some arguing that the negative aspects of employment on the individual have been side-lined [@RN2300]. This is especially prevalent with the fall of some traditionally ‘unhealthy’ jobs, for example, coal mining, and the rise of new jobs considered unhealthy, especially mentally, for example, zero-hour contracts, low pay, ‘flexible’ contracts [@RN2301]. 

Individuals with severe mental illness like psychosis and BPD have difficulty in finding and retaining employment due to the challenges of dealing with their condition. They often find it difficult to balance the demands of the job with activities of daily living (including getting to and from their place of employment) and, at times, these demands can provoke their illness. Studies show that the jobs that people with severe mental illness do are mostly low paying, limited hours and with few opportunities for career progression and improvement in social standing [@RN2375]. Although most studies show disappointing employment outcomes for those with severe mental illness [@RN2370], most report that obtaining paid employment is an important goal for them [@RN4741], personally, socially and often marks an important turning point in ‘recovery’ for those living with severe mental illness, as well as being seen as an important goal by the professionals in the medical and social systems those with severe mental illness deal with [@RN3536; @RN2372; @RN3434]. 

Most people living with severe mental illness have the desire to work, but they are more likely to experience adverse employment outcomes than people without severe mental illness or common mental health disorders [@RN2370]. The literature indicates that employment rates for people with severe mental illness is much lower than the general population, sitting at 12.9% in the United Kingdom. These findings indicate that severe mental illness has a significant economic burden on the individual, their families and health and social systems [@RN2370]. Studies looking into full-time employment of those with severe mental illness found those in employment ranging from 25% to as low as 2% [@RN2372]. Furthermore, after entering employment, the rate of resignation in people with living with severe mental illness within one year was more than 70%, with a mean duration of staying in the job between 3 to 6 months, with reasons for resigning including a lack of motivation, stress, and difficulties with social, professional and romantic relationships [@RN3536; @RN4764]. A synthesis by Kinn and colleagues further supports these findings in their analysis of 16 Qualitative studies published between 1990 & 2011. Their work was conducted to pinpoint the enablers and barriers of employment in people living with severe mental illness. Major themes identified were similar to Choi and colleagues in 2020 and included fighting inertia brought on by their condition, the lack of encouraging peers, managers or mentors, taking control or feeling the loss of control, disruption in their work due to dealing with the day to day realities of their illness, lack of opportunities and support in the workplace, managing the fallout from self-disclosure in the workplace, general environmental factors, clarity of their work roles & lack of social cohesion [@RN3540; @RN3536]. 

### Concepts

It is hard to disentangle the concepts of economic activity and inactivity, employment, and unemployment from the infringement of psychiatry within this sphere, especially for those living with severe mental illness. Some argue that this has been a key goal in a capitalist society as it legitimised and normalised not only the increased consumption of goods as an indicator of success, but the normalisation of exploitative and unequal working relationships and work as an indicator of *“recovery”* for those with severe mental illness [@RN2236; @RN2298]. Cohen in his 2016 work argues that psychiatry’s role has only moved from the social control exerted in asylums – in which *"work therapy”* was popular [@RN2379] – to reinforcing workfare ideologies within the individual, much like distress, onto precarious workers in a neoliberal and capitalist society [@RN3511; @RN20]. With the decline of traditional manual labouring jobs and the rise of white-collar jobs, the labour force was under pressure to adapt and upskill to new social and critical thinking skills. Elraz [@RN2381] uses the term the *“sellable self”* in which the individual must perform the constant expectation that they will manage their impression, promote themselves and sell themselves on the labour market as a product with no faults, weaknesses, or limitations. Through this, psychiatric intervention was encouraged, either to produce a *“happy worker”* or to encourage those already living with severe mental illness to conform to these new expectations [@RN2298]. This idea of positive thinking has been interwoven into the experiences of many going through the benefits system, whether they can work or not [@RN2264]. Cohen [@RN4742] argues that what is seen as negative thinking by employers, work coaches, and mental health professionals is the ability to engage critically with one's personal circumstances within a wider social and political context. This is particularly relevant for individuals living with severe mental illness as they may have a deeper understanding of the societal and political factors that contribute to their experiences. Cohen suggests that this type of thinking is often misunderstood and dismissed as negative, rather than recognized as an important aspect of understanding one's own experiences and the broader societal issues that affect them. This is at odds with the view of the economically active or inactive individual in a neoliberal society, with the mental health professions seeking to place the distress within the individual themselves as a failure to conform to the new notion of positive thinking [@RN2236]. In contrast to these views, mental illness can be seen to be the complete opposite in the workplace, with individuals struggling with poor relations, professional and social, *“negative”* traits such as being introverted, pessimistic, shy, or low mood. 
Some scholars have viewed this through the lens of Marxism and note that the increasing alienation of the workforce in a neoliberal, capitalist society leads directly to greater incidence of mental illness [@RN2382]. Whereas Cohen argues that the context of the mental health and employment systems also need to be considered, that the narrative that precarious conditions experienced are inevitable, with recent psychiatric labels increasingly absorbing this narrative in relation to employment and recovery [@RN4742]. Instead of reassuring individuals that the widening power imbalances in work are real, the changing nature of psychiatric labels encourages individuals and professionals to view the problem within themselves, rather than an issue inherent to wider societal context [@RN4734]. Some examples of psychiatric labels which problematises undesirable behaviour within the workforce are BPD and generalised anxiety disorder [@RN3412]. 

As Pilling in 2022 and Rimke in 2018 in argued, the mental health system does not exist in a vacuum, but has a track record of upholding the current societal norms and expectations through its work [@RN4734; @RN3412]. When certain individual behaviours are viewed as societally unacceptable, especially within a neoliberal society, the mental health system individualises and pathologises this behaviour, a current example being personality disorders [@RN4716] and a historical example being hysteria. Taking hysteria as an example, Novais and colleagues briefly discuss the historical context where they argue that the term has reflected societal views about health, religion and relationships of women in particular [@RN2383]. The term was used in ancient cultures as a catch-all for socially unacceptable behaviour in woman, to its being redefined as *“neurosis”* by Charcot [@waraich2018life], to Freud redefining it as a re-experiencing of past psychological trauma [@freud1955notes]. Then histrionic personality disorder (HPD) first made an appearance in the Diagnostic and Statistical Manual of Mental Disorders III (DSM-III), the only disorder that kept the term derived from the old concept of hysteria, and is still present in the most recent iterations of the DSM V and ICD-11 [@RN3458; @RN2383]. The success of the mental health system in constructing this psychiatric label is seen in the larger number of individuals self-identifying or seeking treatment for these behaviours. That is the ultimate placement of distress within the individual, to the extent their personality is *“disordered”*, their traits *“non-sellable”* on the labour market, with many employers holding negative views of disgust towards those with personality disorder [@RN2319] while ignoring the social and political contexts around them. Rimke in 2018 argues that socially acceptable behaviour, especially in woman, has been narrowed to such as extent that being extroverted and socially active within a community – social or professional – is not just desirable, but obligatory [@appignanesi2011mad]. 

Cohen in 2016 points out this pathologising of behaviour reflects neoliberal capitals societies desire for *“emotional labour”* within the work force [@RN4742]. From the mental health system utilising work as a form of *“therapy”* for idleness in the asylums to encompassing dominant neoliberal ideals of employability and productivity in the current DSM and ICD. Reinforcing the ideological view for workers to locate their distress as an individual problem rather than their reality of exploitation under capitalist society [@appignanesi2011mad].

### The Impact of Economic Activity on Mental Health

Contrary to other departures from the labour market, such as leaving to study, or parental-based leave after a birth, unemployment departure seems to have the most negative consequences for those affected, particularly in relation to mental health [@RN2312; @RN370], with the duration of the unemployment period seemingly connected to the amount of distress experienced. Thill and colleagues found that longer periods of unemployment eventually resulted in a ‘plateauing’ of symptoms experienced by those with common mental health disorders [@RN2385; @RN370]. In the case of those living with severe mental illness, longer periods of unemployment were associated with a further deterioration in symptoms, and an increase in distress [@RN3536]. 

Work by Milner and colleagues [@RN373] described a strong association between length of unemployment and distress experienced, with longer unemployment periods also associated with a significantly higher risk of suicide even before adjustment for prior mental health conditions [@RN373]. This link between economic activity or inactivity and increased distress resulting in suicide has been a topic of increasing concern, especially for those caught within a punitive welfare system, dealing the stigmatisation of being a benefits recipient, and dealing with the view that links social value with ‘productivity’ while conceptualising welfare entitlement as an economic burden that must be stopped [@RN4742; @RN188]. This demonisation of the non-employed, whether economically active or inactive, has become increasingly dominant in the UK and the significant psychological impacts are well documented. Work by Williams in 2021 found that punitive welfare policies such as benefits sanctions, which policymakers claimed would lead to positive societal and individual impact following positive employment outcomes, in fact had the opposite effect. Analysis found that JSA sanctions lead to an increase in self-reported anxiety and depression, as well as an increase in prescriptions for depression, with negative impact particularly evident for sanctions of a longer length [@RN3516]. Qualitative research backs these results, finding an overarching link between these punitive policies and negative effects on individuals mental health, physical health and social and social and cultural capital [@RN4743; @RN3549; @RN2388; @RN3517; @RN4744; @RN3511].

Just as type of employment can have an impact on an individual’s mental health, the quality of their employment can also have an effect on their mental health, which can be particularly relevant for those managing a severe mental illness [@RN2375]. Previous research has highlighted the adverse effects which being in a precarious position within the labour market brings. Insecure employment such as zero-hour, ‘flexible’ contracts, and shift work has been shown to be particularly bad for individuals’ mental health, security and social standing [@RN2394]. 

This work by Ralston and colleges in 2022 assessed levels of employment scarring for those aged 36–39, at Census 2011 (considered prime employment years) who were recorded as NEET when aged 16–19 at Census 1991 in Scotland. They found evidence that NEET status lead to long-term scarring associated with economic inactivity and unemployment and that this was only partially offset for those who moved from NEET in 1991 to be economically active in 2001. Additionally, the results also highlighted the gendering of NEET outcomes, showing that this is not just a problem of administrative convenience but one that captures a group who experience disadvantage [@RN4821]. This is in line with the findings of Henderson and colleagues who found in their longitudinal Next Steps study of 7,700 young adults, that those in insecure employment, such as zero-hour hospitality work, reported feeling less psychologically healthy, and were more likely to report a mental illness than their employed counterparts with contracted guaranteed hours [@henderson2006meanings]. These findings highlight the importance of NEET as a marker of long-term disadvantage and the need for policies and interventions to address this issue.  

Modini and colleagues systematic review on the benefits of ‘good’ employment for those with severe mental illness also supported this view. They state that secure employment could help in the recovery from severe mental illness, with mental health outcomes being positively associated with favourable workplace conditions and good-quality supervision, and insecure employment potentially contributing to worsening symptoms [@RN371]. However, of the eleven studies identified in their systematic review, only four were deemed to be of moderate quality, calling into question their findings based on the quality of the evidence used. Marwaha and colleagues looked into the contribution of employment to the recovery of individuals living with severe mental illness and they found overall levels of employment for individuals with schizophrenia has declined in the past 50 years. Working was correlated with positive outcomes in social functioning, symptom levels, quality of life, and self-esteem [@RN154].

A recent qualitative study by Poulter and colleagues [@RN2396] into in-work poverty, mental health and health behaviours found that, for those with mental health issues, poor quality work led to poorer health behaviours, due to overloaded cognitive functioning: for example, having to plan for unexpected bills, organize food and arrange childcare while managing restricted finances, practical barriers, and work stress. This resulted in health behaviours borne out of necessity for some participants, including giving up food so their children could eat, foregoing dental and eye exams due to cost, and viewing exercise as a luxury as well as being too physically exhausted to contemplate it. One participant shared their experience of forced eating behaviours: 

> *“I have been that poor [when] the kids
> have gone to their dad’s I have like not > eaten [. . .] just so you know you’ve got > enough for the next day if when they
> [children] come home, that’s how bad
> wages were.”* (Participant 1 in Poulter
> et al, 2022, p. 9)

This quote highlights the ways in which economic inequality and poverty can have a disproportionate impact on individuals and families, particularly those with children. It illustrates the ways in which systemic issues, such as low wages and lack of affordable healthcare, can perpetuate cycles of poverty and poor health. Additionally, it brings attention to the ways in which individuals living in poverty are forced to make difficult choices, such as giving up food, that can have a negative impact on their physical and mental well-being.

## Policy Related to Severe Mental Illness and Employment.

This section reviews relevant literature regarding policy concerning employment and severe mental illness in the UK. An overview of the main context is provided before more in-depth review of the evidence of policy impact.

### Context

In recent years, there have been significant changes in the labour market, including the decline of unionisation, the rise of precarious and insecure work, and the increased use of zero-hours contracts. These changes have had a significant impact on workers' mental health and well-being, particularly for those living with severe mental illness such as psychosis.

In addition to these changes in the labour market, there have also been broad changes in welfare policy, including reduced entitlements and increased conditionality. These changes have further exacerbated the challenges faced by individuals living with severe mental illness, who are already at a higher risk of poverty and economic insecurity.

The shift towards care in the community, which began in the 1980s, was intended to provide more flexible and personalized support for individuals living with severe mental illness. However, in many cases, this shift has led to a reduction in funding and support for community-based services, leaving individuals with severe mental illness with fewer resources and less support than before. This, in turn, has led to increased pressure on individuals to find and maintain employment, despite the challenges they face in doing so [@appignanesi2011mad].

Until the 1950s, people with severe mental illness were confined to asylums, where many individuals would stay for most of their lives [@RN4742]. The introduction of antipsychotic and antidepressant drugs and increasing societal concern over human rights infringements taking place within the asylum system led to the gradual closure of most asylums with the support of communities and government [@RN4745], leading to ‘care in the community’ in the 1980s. This deinstitutionalisation occurred with the aim of increasing quality of life for people living with severe mental illness, as well as a bid to reduce costs, and leading to the creation of Community Mental Health Teams (CMHT) and related interventions [@RN2399].

The shift towards community-based care for individuals living with severe mental illness  has had a significant impact on the opportunities and possibilities for employment. Historically, those living with severe mental illness were often confined to asylums and institutionalized settings, with little opportunity for work within the mainstream labour market. However, with the move towards community-based care, individuals with severe mental illness are now able to access a wider range of employment opportunities [@RN4742].

This shift towards community-based care has also been accompanied by changes in the labour market, as stated, these include the decline of unions, the rise of precarious and insecure work, and the increased use of zero-hours contracts. The unpredictably this brings, is a particularly difficult-to-manage barrier for people with severe mental illness. Changes to employment have had a significant impact on the ability of individuals with severe mental illness to secure and maintain employment. Additionally, changes in welfare policy, including reduced entitlements and greater conditionality, have made it more difficult for individuals with severe mental illness to access the support they need to participate in the labour market.

While the shift towards community-based care and greater employment opportunities for individuals with severe mental illness is a positive development, it is important to recognize the challenges that this shift has also brought. The changing labour market and welfare policy can make it more difficult for individuals with severe mental illness to secure and maintain employment, and it is essential that appropriate support and accommodations are in place to help them succeed in the workforce. This includes providing education and training opportunities, as well as addressing the barriers that can make it difficult for individuals with severe mental illness to participate in the labour market. One direction active labour market policy concerning severe mental illness has gone in is vocational interventions and individual placement and support (IPS) programmes [@RN4746], aimed at encouraging re-employment. With unemployment being a risk of living with severe mental illness, not only does it reinforce social and economic isolation and marginalisation, but it can also worsen symptoms [@RN208]. With the onset of conditions like psychosis peaking in early to mid-twenties the disruption of dealing with this can severely impact on educational attainment and the building of necessary employment skills and work history. Especially in the case of younger people with psychosis, this disruptive period can have a particularly negative effect on employment throughout the lifetime. Following on from a key government message from the *‘Work, Recovery and Inclusion’* report [@RN4747] that work is good for the recovery and mental health outcomes of individuals with severe mental illness, there has been a push to help this group into meaningful employment. One promising intervention seems to be the Individual Placement and Support intervention. This particular intervention places focus on supporting all individuals who want to return to work in competitive job searching, regardless of symptom severity or readiness at that time [@RN3576].

These policies and outcomes have been fuelled in part by increasing ‘poverty propaganda’ and demonisation of the working-class and those with severe mental illness in particular [@RN4748]. This is, in part, due to the rise of food banks for example, becoming a very public example of policy direction. The paper by Ralston and Gayle explores the concepts of *"generations"* and *"cultures"* of worklessness that are often used in political and media discourse [@RN4820]. The authors use data from the British Household Panel Survey to investigate whether these concepts are supported by evidence, and they find that there is no evidence to support the belief in generations or cultures of worklessness. Instead, they argue that these concepts should be considered as improperly held beliefs and that it is time to abandon them. This conclusion is significant because it challenges the narrative that is often used to justify policies and outcomes that target the working-class and those with severe mental illness [@RN4820].

Additionally, the popularity of so called *"poverty porn"* typified by programmes like ‘Benefit Street’ have provoked public and political debate about the realities of poverty and its fallout. Punitive policies towards benefits claimants, austerity measures and the proliferation of low paid and insecure work mean poverty has been extended to more and more people, yet at the same time it is a condition that is still stigmatised, misrepresented and misunderstood [@RN4748; @RN3547]. 

### Concepts

Recovery as a concept for moving those with severe mental illness or common mental health disorders and out of work, appeared in English mental health policy in 2001 and shortly after in the rest of the UK. It reflected frequently cited grass roots user-led definition, which originated from people with severe and enduring mental health conditions in the United States in the 1980’s. Despite recovery’s prominent place in policy, little was known about what recovery services would look like or the barriers to implementation in the UK. Recovery in the Bin note that recovery’s prominence in policy in 2001 was highly political and neoliberal. Recovery was therefore enacted in policy and services implemented it [@RN2236]. However, there was little guidance on how this would be possible and they were seemingly unaware of the politicised nature and the potential harms that it could cause. In this context the concept of *"neorecovery"* emerged - reflecting the neoliberal, capitalist context of society and mental health services in its approaches and practices, with its emphasis on individualism, 'responsibility', 'dependency' and work as a health outcome. It has been widely acknowledged that recovery’s implementation in the real world is inconsistent, with recovery interventions such as the REFOCUS trial and Recovery College suggesting that a UK social and political context poses considerable barriers to ‘recovery’s’ effective implementation [@RN3577]. 

Recovery in the Bin argue that after years of sub-optimal implementation of recovery policy and interventions, a new recovery approach emerged from the neoliberal climate – neorecovery. This shift in focus created a ‘one size fit all’ approach to everyone using mental health services, and coupled with policy needs, resulted in time-sensitive treatment that focused on ‘work’ as a key indicator of recovery and successful movement through treatment, discharge, and return on investment, with no difference between common mental health disorders or severe mental illness. This approach is underpinned by neoliberal individualism and compulsory positivity, which has resulted in neorecovery catering for the societal norm, the socially acceptable and the majority who have mild to moderate difficulties. Slade and colleagues in 2014 point to this redistribution of resources from inpatient and secondary care to primary care, and the prioritising of low intensity, short-term, low-cost ‘interventions’, the closure of wards and day centres in the name of individual recovery as an abuse of the concept that places the onus on the individual while ignoring the social and political climate and the complex nature of living day to day with severe mental illness [@RN3577]. 

### Evidence of Policy Impact

Practically, rolling individual placement and support (IPS) interventions to mental health services proved difficult, as the following work by Slade illustrates. Surprisingly, this was not due to the ambivalence of treated individuals, but due to their care team discouraging participation due to fear of employment exacerbating symptoms or causing a relapse. As such the IPS intervention was trialled alongside motivational training for the mental health care team [@RN3577]. This cluster randomised controlled trial included four early intervention teams in London and the Midlands. All teams included a specialist trained in delivering the Individual Placement and support intervention, with two teams receiving the additional motivational training. This motivational training included techniques that aimed at addressed staff concerns around the risks and values of individuals with psychosis returning to the labour market. Participants were receiving management within the early intervention in psychosis services, which serve people aged between 18 and 35, and were not in work or full-time education. The primary outcome of the trial was the number of individuals in paid employment at a 12 month follow up. Only 160 eligible participants consented, with one later withdrawing. The remaining 159 individuals expressed a strong desire to return to work, but not think it was likely they would do so due to a number of reasons. At the 12 months follow up 24 of the participants had been lost, 29 of the 68 individual within the intervention plus motivational training group were employed in comparison to only 12 of the 66 individuals in the intervention alone group. However, weaknesses included that motivational training was poorly attended by clinicians, psychologists and psychiatrists especially did not attend, with just one of three clinical psychologists only attending one training session of the block. Out of the potential participant pool of individuals receiving management through the early intervention in psychosis services, only half of the eligible individuals consented to participate, potentially biasing the randomised trial from the start. 

Craig and colleagues follow-up clusters randomised controlled trial [@RN4749] provides new evidence that a major barrier for poor employment outcomes in people living with psychosis, is a lack of encouragement and low expectations of their care team and wider staff within the mental health services they attend. Although these negative views from professionals could be based on prior experience, , they give people with severe mental illness a hostile environment in which to operate and consequently, are highly damaging towards those they are trying to help. Previous research has shown that prolonged absence from the labour market and delaying re-employment when feeling ready can have more of a negative impact and be more likely to provoke a relapse, than a return to work would [@RN4750]. 

Craig et al’s 2014 randomised controlled trial aimed to evaluate the effectiveness of an individual placement and support (IPS) intervention in improving employment outcomes for individuals with psychosis who were receiving management through early intervention services. The trial included four teams, with two of them receiving additional motivational training for the mental health care team. The study's findings suggest that mental health staff within primary services for psychosis need to be more supportive of their patients' desire to return to work, rather than being overly cautious about potential risks, which may negatively impact the overall outcome. The use of a randomised controlled design allows for the examination of cause and effect relationship between the intervention and outcome
[@RN2236].

Reduced local resources that support community living, disproportionately impact at-risk groups like older people and those living with poor mental health [@RN4751]. Those living in deprived communities are more likely to be isolated, and more affected to cuts to free community resources [@RN4752]. Isolation is known to precipitate and hinder recovery from poor mental health [@RN4753]. It has a comparable mortality risk to smoking and drinking alcohol and is a higher risk for mortality than obesity [@RN4754], with Britain having one of the highest levels of isolation in Europe [@RN1111]. Community-level service cuts have also removed many choices from day-to-day living for those struggling with poor mental health and low incomes, leading to feeling trapped and powerless. For example, the cuts to legal aid have resulted in many people not having help to deal with crucial areas like housing, family, debt, or benefits [@RN4755]. Feelings of entrapment have serious short and long-term impacts. It is a key cause of anxiety and depression [@RN4756], and feeling powerless is a key symptom in many complex mental health conditions like psychosis and schizophrenia. Poor mental health is in part, a complex response to difficult life situations and circumstances, so trapping people into situations that involve abuse, trauma, and neglect on individual and societal levels can create lifelong issues.

## Exploring Severe Mental Illness With Data

Administrative data offers an invaluable opportunity to explore the aims of this thesis and was the original data envisioned before the COVID-19 pandemic forced this work to be reorientated as discussed previously. Even though this no longer played a role in the analysis from 2020 its inclusion here reflects the substantive body of work undertaken before this thesis had to change. Its increased availability means vital research that could result in positive policy change can happen in a safe and secure way [@RN4758]. There are, however, differences in comparison to traditional research and data collection, as administrative data is collected when individuals interact with services, and not solely collected for the purpose of research. This section discusses the strengths and weaknesses of administrative data research before providing an overview of the data sources relevant to this thesis.

### Context 

Administrative data is generated when individuals interact with public services, such as schools, the NHS, the courts, or the benefits system, and collated by government. These services keep records of these interactions for operational purposes in order to carry out their day-to-day work, to monitor and improve their performance, and to keep providing services in an effective way [@RN4758]. For example, the NHS records details of admissions and appointments to monitor trends in hospital activity and patient care. Administrative data also includes basic information about people in the UK, such as notifications of births, deaths and marriages, the electoral register, and the censuses [@RN4758]. 

Using administrative data for research comes with a number of strengths and weaknesses. One weakness is that the data is not collected exclusively for the purpose of research and could lack specific relevant information [@RN3578]. This also reduces the ability to adjust for confounding variables, and decreases the ability to draw potential causal inferences. The coding of variables, especially more subjective variables, could be ambiguous, even if there is good documentation available. Quality of the data can also be an issue, especially high levels of missingness [@RN3578]. Missingness can happen for the same reasons as in traditional research meaning data was not available to input into the database, but could also be because state-funded employees redact data files. Administrative data may also have issues with structure, which along with coding issues and missingness can make it complex to work with, with extensive data cleaning often needed in advance of analysis [@RN3578].

There also remain significant, ongoing problems within psychiatric science in validating psychiatric labels – which are the main method of identifying severe mental illness and common mental health disorders within administrative data - and accurately defining, measuring, and explaining classification [@RN4742; @RN4759]. A recent assessment by Allsopp and collegues [@RN678] of the major psychiatric labels in the DSM-5 concluded that the labels were “scientifically worthless as tools to identify discrete mental health disorders” [@RN678]. With the relationship between psychological, social, and environmental factors and any ‘mental illness’ continuing to be vague and imprecise [@RN4742], this is less surprising given the validity issues above.

Advantages of administrative data, however, include that they are often large cross-population sample sizes, because they are generated from using a service, which can mitigate against potential sampling bias. Another advantage is that well-maintained data produce information over an extended period of time, with the ability to ‘track’ certain populations or phenomena. This could be argued to make inferences from these sources more robust with good external validity, and without incurring costs seen in traditional observational studies [@RN3578].

### Alternative Data Capturing Severe Mental Illness and Employment

The aim of the original thesis was to use novel linkage of health and other administrative data to explore the relationships between severe mental illness and employment outcomes across the lifespan. However, due to the impact of COVID-19, access to this data was lost and other data sources had to be considered. (See Chapter \@ref(chapter3)). Data was needed that not only met the requirements of this thesis’ research aims and questions but could also be accessed from a home working environment. The data that was finally settled on was the Adult Psychiatric Morbidity Survey (APMS). This series of mental health surveys consists of four repeat cross-sectional surveys. The first two covered Britain (England, Scotland and Wales) and were conducted in 1993 and 2002 by the Office for National Statistics (ONS). The 2007 and 2014 surveys covered England only and were conducted by the National Centre for Social Research (NatCen), with the most recent – 2014, and 2021 – being commission by NHS Digital. The APMS sits within a wider series of general population surveys examining the mental health of specific populations. These have included people living in institutions, the homeless population, the prison population, carers, and minority ethnic groups. There has also been a series of mental health surveys of children and young people in England carried out [@RN3582]. A full description of these data sources, the variables used, and the process of analysis are provided in Chapter \@ref(chapter3).

## Conclusion

Ultimately, it is important for individuals living with severe mental illness to have access to meaningful and safe employment that can enrich their lives, instead of falling into social exclusion and marginalisation from the general labour market through lack of opportunity or understanding. As a concept, severe mental illness is more complex than many realise, and still suffers from validity issues and ambiguity in terms of definition. There most direct way measuring severe mental illness in administrative data for research purposes is via psychiatric labels, even though the concept has ongoing issues. Debates about impact and dimensions of the systems individuals with severe mental illness interact with, particularly in relation to mental health and employment continue to highlight the ways in which these systems can operate to depoliticise and individualise distress within the individual. Despite concerns about the negative impact of public services and policies on certain individuals, there is evidence that many people, particularly those facing multiple disadvantages related to deindustrialization and the decline of working-class employment opportunities, understand the ways in which their lives are limited by these factors and further impacted by mental health issues. This is why exploring these relationships between severe mental illness and employment is of high policy interest.

Routinely collected administrative data would have offered an interesting opportunity to address this. Recent advances in infrastructure and training in administrative data research has, permitted this investigation of difficult questions to go ahead, whilst maintaining data privacy and compliance with legislation, even in light of COVID-19 disruption. However, using surveys in this thesis was a valuable approach for several reasons. Firstly, surveys allowed for a more in-depth examination of the experiences and perspectives of individuals regarding their mental health and access to employment opportunities. This provided a more comprehensive understanding of the issues being studied, as opposed to relying solely on administrative data. Additionally, surveys allowed for the inclusion of a diverse range of participants, including those who may not have been captured in administrative data sets. 

While it is true that the use of routinely collected administrative data would have offered an interesting opportunity to address this research question, the use of surveys provided a more comprehensive and nuanced understanding of the issues being studied.
