---
output:
    thesisdown::thesis_pdf: default
bibliography: bib/thesis.bib
csl: csl/harvard.csl
space_betwee_paragraphs: true
fig_caption: true
always_allow_html: yes
link-citations: true
toc-depth: 3
lot: true
lof: true
editor_options: 
  chunk_output_type: console
---

# Methods 2: Reflexivity {#chapter4}

## Chapter Overview

This chapter outlines a description of and critical reflection on this project’s autoethnographic reflexive methodology. In Section 4.1 I consider the application of the quantitative approach to individual experiences. Section X and X considers my professional and personal relationships to this project and its topic. Section X sets out the need for reflexivity in quantitative methods. 

## Quantitative Methods & Personal Experiences

This project applies quantitative methods at the heart of its exploration into the relationships between Severe Mental Illness and employment outcomes. A distinction made when exploring research methods is the differences between quantitative and qualitative approaches, which are often portrayed as a dichotomy [@RN3587]. 

The quantitative approach stems from positivism which is realist orientated and based on the view that reality exists independently and can be described as it is. Ontologically the approach holds that one ultimate truth exists and objective reality exists independently of human perception [@RN3425]. Since phenomena have objective reality in positivism, quantitative epistemology states that the researcher and that being investigated are independent entities and therefore the researcher can study a phenomenon without influencing it, or being influenced by it [@RN4762]. It also suggests that facts and values can be separated, allowing the researcher to explore this truth as their work aligns to the reality being investigated. As a result, it regards this truth as validity. To eliminate threats to validity, various research strategies are implemented to ensure biases are prevented from influencing the outcomes, with are then viewed as true [@RN4763]. Within this approach objective reality can be viewed in terms of causal effects that could allow generalisable prediction. Consequently, the aim of this type of investigation would be to measure and analyse causal relationships in phenomena , but also about the description of the scale or nature of phenomena or trends over time, or the identification of (non-causal) relationships or associations within a value-free framework with the end goal being generalization. This type of methodology can be described as unusual, with questions and hypothesis proposed, tested, and verified, with confounding conditions controlled for to prevent outcomes from being biased [@RN4764].

Given that generalisation and objectivity are underlying principles, the positivist quantitative approach calls for methods grounded in statistical analysis, such as inferential statistics, hypothesis testing, experimental and randomisation design, structured protocols, and questionnaires with predetermined responses. Sample size is also critical in quantitative research, with large samples ensuring better representativeness and generalisability of findings alongside the proper use of statistical tools. 

## *"Where Am I?"* The Researcher in a Quantitative Context

Research is not conducted in a social or political vacuum and our work will always be inevitability informed and influenced by our individual experiences and conscious and unconscious biases we hold. Although more discussed within qualitative methodology, there are also arguments within quantitative methodology that objectivity cannot truly be achieved [@RN4718]. Work by Lazard and McAvoy raises that reflexivity does occur within all research to some degree, no matter the methodology. The view that objectivity is fallible even in quantitative research conflicts with the view that sound knowledge production only comes with research in which the researcher is detached from the subject and are themselves unbiased, and the decisions made in collecting and processing the data from start to finish can be laid open to scrutiny and challenge. The search for objectivity became interwoven with the common assumptions held by the researchers, and the context that they worked and lived in. Harding [@RN2419] argued in their work ‘The Science Question in Feminism’ that science rests on a set of socially, politically, and historically produced dualisms such as, objectivity/subjectivity, rationality/irrationality that links males to the former and females to the latter in each dichotomized pair. Harding argued that these dualisms became influenced due to the privilege afforded to one half of the dichotomy over the other, objectivity, rationality, science (or quantitative methodologies) and masculinity became privileged or seen as more worthy than subjectivity, irrationality, and non-science (or qualitative methodologies) and femininity by virtue of their position in the pairing. These relations of power are important because, as Harding in 1986 points out:

> *“these beliefs (from science) structure > the policies and practices of social
> institutions including science [itself]”* ([@RN2419], p. 136).

These critiques created a legitimate basis for calls to work with subjectivity rather than against it in quantitative methodologies [@RN4718; @RN2410]. 

To counter this, I can provide an honest account of our own position and reasonings in approaching this research, one way being to engage in reflexive practice [@RN3512]. Reflexivity is a form of critical thinking which aims to articulate the contexts that shape the processes of doing the research and the subsequent knowledge produced. It is meant to be a steady, internal assessment, and often an uncomfortable experience examining the dynamics between the interpersonal and external knowledge production taking place around you, the researcher. Through these internal dialogues, researchers can account for their personal circumstances and acknowledge their stance in relation to the research [(@RN3512]. This section provides this short reflexive account and the ontological and epistemological underpinnings that have helped shape this research, and the personal and professional influences on the whole research process that occurred. 

Professionally, I am a researcher with a background in psychology, although I now describe my work as interdisciplinary and better for it. Mills [@RN4765] considered the role of the social scientist as being able to turn individual issues into issues of public concern. Through raising awareness of these ‘personal troubles,’ private and individual issues by contextualizing them in the inequalities throughout society, such as the imbalances at play in class, gender, and race. Contrary to the usual positivist approach seen in traditional quantitative methods, I approach this research from more of a social constructionism position, where knowledge is viewed as something generated through interaction, and something I argue also happens within quantitative research, and is much less considered than its qualitative counterparts. 

My professional identity also has been influenced by my personal and professional alignment with intersectional feminism. Feminist approaches to research generally question the normative assumptions of what ‘good’ research is, and this is seen to be evidence-based, objective and conducted by non-biased researchers [@RN3512]. However, as discussed in this chapter, this idea of ‘hygienic’ quantitative research is in fact both affected by and affects the researcher, consciously or unconsciously. Subsequently, the researcher is present in the research process, and inextricably involved in the construction of knowledge, regardless of its qualitative or quantitative methodology [@RN3512]. 

Personally, I am white, neurodiverse, able-bodied, bisexual, and non-binary. I grew up in a working-class, single-parent household, in the working-class area of Pollok in Glasgow during the '90s and '00s. These have been some of the background factors that have helped to shape my experiences of the world, and it is important to note the privilege this has afforded, even though the act of being able to conduct this research. However, despite this, this research grew from my own lived experience or ‘personal troubles’ [@RN4765] associated with severe mental illness and navigating employment. I grew up affected by severe mental illness, violence, and substance abuse in my family. Throughout my childhood and teen years, I became the primary carer for both my mother and father in turn as I lived between both households, and in between significant events that would move them in and out of my life, and in and out of employment, such as hospitalisation, care experience, and imprisonment. Going into my twenties I was maintaining a lot at once, my own poor mental health, employment, caring responsibilities, and education.

Throughout my early twenties I became more aware of the state of my own mental health, which included panic, anxiety, and disordered eating, but continued to ‘place it on the back burner’ to continue with my responsibilities, even as these were having a profound impact on my own health and wellbeing. In the summer of 2017, while finishing my MRes dissertation and looking at further study, I suffered what would later be described as a ‘first episode of psychosis’ following several incidents of assault. I found this very difficult to process in the context of my life at the time as my self-worth was tied to my ability to produce, especially academically and this episode I felt was hindering this. I felt internalized shame for my own poor mental health and working-class background, as not being able to continue academically meant, in my mind, I would fall back into the unemployment and welfare ‘trap’ that so many people around me at home had struggled with, and that I had struggled with years before. I struggled with shame from the stigma of having a family history of severe mental illness, and due to this background began to believe that this episode was a self-fulfilling prophecy and that I would never be able to ‘escape’ my background [@RN4766; @RN4767]. I felt unable to speak to family and friends about the situation. My family, when it was mentioned, believed that employment was a route to recovery, but that only the ‘right kind of work’ would achieve this, and this did not include academia. I became known to my GP and low-intensity mental health services in what would become a long process in getting proper support and starting therapy. In the interim I was prescribed psychotropic medication that allowed me to function on some level but did not help me process my experiences. 

In the months after experiencing this first episode and dealing with the everyday realities of living with a psychosis condition, I was accepted onto this PhD project, and it was the process of shaping this project into my own that allowed me to think about the experiences that led me to this point. I became concerned that there was not much progression in exploring the impact of severe mental illness in particular on employment outcomes. The existing work too often focused on the impact immediately after diagnosis and concentrated on the myriad of negative statistics surrounding the life outcomes of an individual with certain psychiatric labels. As someone who now lives with one of these conditions, this was upsetting to see, and ultimately what helped drive this project. Not only would this explore these relationships, but I would also be engaging with this quantitatively as someone with lived experience of a severe mental illness condition, and many of the life experiences that those present in the data would have experienced. This, I would argue, is a defining strength of this project – combining the traditionally thought of ‘strengths’ of a quantitative approach, with the reflection and reflexivity in place to understand each step and how this would influence on the approach used. 

Lazard and McAvoy in their 2020 work argue that researchers, especially those used to quantitative approaches, need to and should reflect on their own subjectivity. However, it has also been recognised that within these approaches academics who do share these personal views are at risk of being seen as ‘biased,’ ‘too emotional,’ and of ‘navel-gazing’, while ruining the objectivity of the research, and their professional work often questioned and critiqued for it [@RN3512]. In agreeing with those who support reflexivity in research as valued and needed, I challenge this dichotomy between the subjective and objective, biased and unbiased, public, and private. In this project I do not write these personal experiences as a means of self-gratification or ‘navel-gazing’, or even as a cathartic act. I tell my experiences to contextualise this work and provide a face to the ‘numbers,’ and as points of reflexivity for the reader. I use my own experiences as data [@RN4768] to illustrate the reality of the wider issues within this project, and as a reference for readers to understand the motivation behind this work, and to situate the decisions made throughout this project – from conceptualisation, research design, analysis, interpretation, and write up of traditional quantitative work – through the lens of someone who has experienced similar situations to those present within the data. 

The norm of keeping the personal and professional separate within research has been suggested to be a by-product of the insecure institution of academia. As a profession it tends to result in academics adopting ‘academic armour’. The wearing of this armour leads to protection of reputation, but also in emotional detachment, which Lerum in 2001 argues has become synonymous with objectivity as the gold standard, within quantitative research especially [@RN2419]. Lazard and McAvoy also warn of the danger of holding objectivity within quantitative research as a cornerstone of ‘expertise’ – which can gloss over issues such as power imbalance, colonialism, classism, racism between the researcher and the researched [@RN4718]. By dropping this armour, we could become more personally and emotionally engaged in the work through reflexivity, whilst also being challenged to acknowledge and defend our professional position. 

Others who have included personal and lived experiences in their research have done so to challenge the status quo about who or what qualifies as ‘academic’ but have also held fears that this would diminish reputation or have the research trivialised. Work by Sikes and Hall [@RN4770] and Mills [@RN4737] argued that bringing the personal into the professional can help break down barriers, especially around fear in academia. And one way to do this is to challenge the view of what equates to valuable knowledge, which we have seen is traditionally from a distanced, objective approach. By integrating these approaches discussed, and conducting reflexivity, this research becomes situated in the ontological and epistemological grounds of challenging the dominant power narratives within traditional quantitative methodologies of what constitutes ‘good knowledge’ that would be accepted in academia. It views the role of the quantitative researcher as having an unavoidable impact on the data chosen – whether they have collected it or not – the analysis, the interpretation, and the write up of findings, as being active in co-production of knowledge even though they are not traditionally interacting with the individuals represented in the dataset. 
## How Reflexivity Can Be Practiced by Quantitative Researchers

If positionality refers to what we know and believe, then reflexivity is about what we do with this knowledge. Reflexivity is thus a form of critical thinking that prompts us to consider the ‘whys’ and ‘hows’ of research, critically questioning the utility, ethics, and value of what, whom, and how we study [@RN4771]. As Lazard and McAvoy [@RN4718], explain, the reflexive process is based around the question *“what is the research process and how am I influencing it?”*. This questioning forms part of an ongoing process that prompts the researcher to continually shift and (re)construct their understanding as part of a process of ‘disciplined self- reflection’. Crucially, reflexivity differs from ‘reflection,’ although the two have been conceptualised as a continuum [@RN4772]. Reflexivity refers to the conscious, active acknowledgement of one's own beliefs, biases, and judgements before, during, and after the research process, whereas, in contrast, reflection is often done retrospectively and typically leads to insights about details that were ‘missed’ in the process. Reflexivity, therefore, has a greater potential to guide the research process, across all research epistemologies and methodologies. Reflexivity is historically a hallmark of qualitative research because of its critical nature as discussed previously by Lazard and McAvoy (2020) and offers much insight to qualitative research. Due to its thoughtful and reflective nature, reflexivity is a cornerstone of successful and insightful qualitative work [@RN4773]. For example, Wiggington [@RN4774], p. 541) discusses the *“light-bulb moment”* they had when they became aware of how their own position as researcher was affecting the questions they asked of their participants, noting how this influenced and shaped their assumptions. Moreover, reflexivity can help researchers to navigate the ethics and emotional labour of their research [@RN4775; @RN4776].

A small body of literature has also considered how reflexivity may be a useful tool for quantitative research. For example, Ryan and Golden [@RN4777] argue that the reflexive lens is an important one for all data collection in sociology, noting in particular how reflexivity can lead to important insights into the emotional cost of researching sensitive topics. They also suggest that keeping reflexive journals throughout quantitative sociological research can provide a useful opportunity to add a depth of understanding to the data analysis. Similarly, in a midwifery context, Kingdon [@RN4778] stressed that reflexivity may be relevant to all research approaches. Kingdon specifically focused on how reflexivity may identify, and thus mitigate, potential researcher biases which may impact clinical care. However, despite these early commentaries, the vast majority of quantitative research has remained seemingly immune to this part of the research process.

The introduction of Conflicts of Interest (CoI) statements has sparked a relevant discussion in quantitative research. CoIs have long been defined in quantitative research as predominantly financial; only recently, discussions have arisen about what other possible, less defined, CoIs might arise, and how to report those ([@RN4779]. In response to this, the question of how reflexivity may benefit quantitative research has also gained renewed momentum [@RN4780].

The first major challenge in making the case for embedding reflexivity into quantitative research is relinquishing the perception of quantitative data as the ‘gold standard’ of objectivity, and more ‘scientifically sound,’ than qualitative data. Stainton-Rogers [@RN4781] suggests, perhaps the time has now come for quantitative scientists to *“face up to and confront the limitations and distortions imposed by… clinging to scientific method”* (p. 5).

Acknowledging that the ‘scientific method’ does carry distortions, biases, and limitations, may give way to a more open-minded approach to research. Indeed, qualitative research is typically more equipped to deal with the study of sensitive areas which may evoke a heightened concern for researcher and participant ethics of care and emotional labour (or ‘emotional work;’ [@RN4782], which makes it especially suitable for reflexivity. Quantitative research, in contrast, is more concerned with providing a numerical summary of ‘patterns,’ including behaviours, responses, and attitudes, for example, through survey methodologies.

However, this epistemological approach does not make quantitative research inherently more objective, robust, reliable or scientific than other approaches. As Farran [@RN4783] argues, statistics are at risk of being perpetually "divorced from the context of their construction and thus lose the meanings they had for the people involved" (p.101). Moreover, quantitative methodology often deals with topics that are thematically all but objective, especially in the social sciences. For example, research on gender differences in the brain can lead to neurosexism [@RN4784], while capturing the complex experience behind living with poor mental health through surveys can lead to binary thinking around treatment plans [@RN2236]. These are topics that have an especially broad impact on society and are distinctly subjective and impacted by the researchers’ political, ideological, and personal agenda. For example, Moss and colleges [@RN4785] note how social psychological fieldwork in conflict settings have practical and ethical considerations, which are heightened when researchers are ‘outsiders’ to the local context of the research. Therefore, how these topics are approached should be handled not only with care, but also with active deliberation through reflexive practice. Moreover, the notion that quantitative approaches are objective also relies on the idea that data are objective. For example, that biases in data get reflected in models and their prescriptions and predictions [@RN4787]. It is, therefore, necessary to question the assumptions that are contained in datasets, noting how these relate to injustice and power asymmetries.

Whilst the ‘Open Science’ movement has set its sights firmly on improving data transparency and the rigour of analysis plans, an appreciation of researchers’ positionality has, to date, been exempt from this conversation (however, see for an exception [@RN4780]. What is more, the fact that the Open Science movement proposes relatively accessible solutions to mitigate researchers’ biases might even create a false sense of (performative) objectivity. It gives the impression that if researchers simply follow the rules proposed by the Open Science movement and science reformers, this will lead to ‘better’  objective research.  The movement aims for transparency so that decisions can be more readily observed and debated, perhaps not necessarily with a view that there is one objectively correct way to analyse any given problem or dataset, but in order that areas of disagreement can be made visible and their implications discussed. This could be argued to widen the debate on reflexivity from a purely personal one to a collective one. This view that purely by eliminating researchers’ subjective biases one can discover the truth does not originate from the open science movement. It is firmly grounded in rationalist thinking, influenced by for example Cartesianism and Newtonianism [@RN4787]. As discussed by [@RN4787], this tradition hosts a fertile ground for dichotomous thinking, for example in subject vs. object. However, it can be argued that even if data are quantitative and numerical, the ways in which they are analysed and, to a greater extent, the inferences made from this analysis, will vary depending on who the researcher is [@RN2410]. 

For example, by engaging in reflexive practice, it can bring biases and unchecked assumptions ‘to the surface,’ which may reduce practices that can impact the credibility and verifiability of research, such as selective outcome reporting and hypothesising after results are known (HARKing); [@RN4788] without proper statistical correction. As Open Science advocates have stressed, there are a multitude of decisions that analysts of quantitative data must make in the data analysis process, which all can sway the final outcome. Acknowledging this ‘garden of forking paths’ goes some way in dismantling the notion that analysis of quantitative data is entirely objective and free from researcher bias. However, we take this analogy one step further, arguing that every step of the research process, from setting out a research question, to choosing a sample, to collecting data, to interpreting their meaning, offers a new ‘fork in the path’ that researchers must contend with. Therefore, there is value in promoting an up-front approach to researcher positionality, biases, and agendas.

### Reflexive Research Questions and Design

A common method for developing and answering quantitative research questions is by identifying a gap in the existing literature and designing a study to address this gap. This fundamental process may benefit from integrative reflexivity, embedding reflexive engagement from the very start of the research journey. For example, it may be useful to embed an explicit consideration of why a particular research topic and not another? Why one population and not another? Out of all gaps in the literature and all the possible research questions asked, why this one? Why is this interesting? And most importantly, why are we best placed - or not - to research and involve this population group, and answer these questions? As Magnusson and Marecek (p. 90) [@RN4790] note: *“knowledge is ‘interested’"*: that is, there is a reason a particular question is of interest”. At the early stage of the research process, bias exists, whether it is hidden under a veneer of objectivity or not. Integrating reflexivity at this stage would include broad questions like ‘what is the research process’ and ‘how am I influencing it?’ and ‘am I the one to answer these questions over someone else?’ This is a method of personal insight, characterised by a persistent questioning of assumptions through a personal dialogue, which has been used in areas that involve qualitative aspects to teach critical inquiry and self-knowledge [@RN4791], and can be integrated in quantitative research methods. At the time of research conception, design, and forming the research questions, this would take the form of internal dialogue as well as conversations with participants, colleagues, and others, including those who may take different perspectives to that which frames the research. This helps the field move away from voyeuristic research that does not further marginalise or Other. It can also inspire co-produced research, in which the people that are affected by the research (“knowledge users'', experts by lived experience or policy makers), are part of the research process. This can apply to any part of the research cycle, from formulating research questions to analysing data or implementing research output [@RN3512].

Moreover, part of the reflexive process should be an ongoing critical engagement with the voices that are heard in the literature review that sets the tone for the theoretical framework and inspires the research questions. Importantly, a reflexive approach to a literature review should attend to one’s own biases and assumptions as a researcher and be prepared to critically evaluate the source of chosen evidence. That is, which researchers are being cited, which researchers are thought to be credible? Research has shown that men are overrepresented compared to women in citation practises [@RN4794], and that White authors are overrepresented compared to ethnic minorities [@RN4795]. Interestingly, in both cases, these trends seem to be driven by the citation practises of white male authors and are mitigated when the research field gets more diverse.

In practice, embedding reflexivity into the early parts of the research practice can be achieved by confronting biases transparently and openly; a simple example is including a reflexive statement in a study pre-registration. In doing so, this practice may prompt researchers to articulate their positionality early in the process, thus allowing space for an acknowledgement of how this may then guide future decisions in the research. This may be particularly useful when working in collaborative teams with multiple researchers. As ‘Team Science’ becomes more mainstream in social and personality science [@RN4796], reflexive statements up-front may provide a logistical answer to the ideological challenge that working with multiple researchers addressing one question may present. If the opportunity for these early conversations has passed, a further way to reflect on how researcher's positionality influences research questions and research designs, and to mitigate bias, is to add a diversity or positionality statement to academic papers, which serve to centralise and confront the presence of bias in psychological research [@RN4797], but should be considered the very least in starting with reflexive practice. For example, in a recent paper lead by Pownall and collegues, authors joining the writing team each wrote a positionality statement on the topic at hand and used this to frame the approach to writing. These individual articulations of positionality were then condensed and shaped, leading to a final consensus on positionality which was included in the final paper to orientate readers to the viewpoint of the collective writing team. Being up-front about viewpoints, biases, agendas, and lenses may lead to a richer, more contextualised final product. There is no ‘one size fits all’ for positionality/reflexivity statements, and authors should feel able to share as much (or as little) of themselves as they feel safe and comfortable with. 

### Reflexivity in Data Analysis and Interpretation

To begin to embed reflexivity into the process of analysing quantitative data, we first need to dismantle the myth that numerical data is objective and textual data is subjective. The ongoing discussion and the adoption of Open Science practises have indeed made researchers more aware of biases that impact the objectivity of numerical data. For example, there has been much discussion about ‘confirmation biases’ (I.e., preferring or seeking out information that confirms, rather than challenges, your world-view) in the context of interpreting data. Lehner et al, in 2008, for example, show that more weight is given to evidence that supports a preferred hypothesis, and given less weight to evidence that disconfirms it [@RN4798]. However, the biases that are addressed by the Open Science movement are mainly *“universal”* biases, that is, biases that are supposedly similar for all humans. Lazard and McAvoy argue that next to biases like the confirmation bias, the need to reflect on researchers’ individual biases, that is, the way in which our personal stories impact the way in which we analyse and interpret our data is also needed [@RN4718].

Practically, reflexivity can be embedded at the data analysis stage in many ways. If reflexive steps were followed from the research inception, researchers would arrive at the data analysis stage with a well-articulated understanding of their own positionality and agenda for the research at hand. They would be well-versed in acknowledging and confronting their biases and will be prepared to 1. transparently centre these viewpoints within the research itself or 2. include safeguards to build in more objectivity into the research process. For either of these approaches, one particularly entry-level way to engage reflexively in data analysis is to keep detailed journal-style notes during the data analysis process. Indeed, this is another example where the quantitative world has much to learn from our qualitative peers. In qualitative research, for example, keeping detailed, thoughtful, reflexive field notes is gold- standard practice [@RN4799]. Field notes provide a useful space for ‘critical reflection’ throughout the research process, which can be used as an analytical tool. In Phillippi and Lauderdale’s 2018 discussion about best practice in field notes, they explain how:

> *“...qualitative research acknowledges
> the role of the researcher as an
> instrument within the research, shaping
> the results”* (p. 386) [@RN4799]

And use this as rationale for note-keeping. This log of decisions could then be made openly available with the data, code, and paper, which would add a concrete level of transparency to the published research. This ultimately improves the transparency of the research, while also remaining attentive to researcher’s own decisions. A log journal similar to this is easily built-in open science platforms such as GitHub and Open Science Framework [@RN2410]. 

### Reflexivity in Conclusions and Framing

The ways that data are interpreted, conclusions drawn, and the ‘framing’ of analysis all reflect the researcher’s biases and lived experiences, and how the evidence that is used to contextualise and frame our research findings also reflect personal biases and assumptions. For example, in a discussion about the role of political ideology, Harper [@RN4800] argues that ideological biases drive citation practice. That is, a study reporting gender bias in academic hiring was cited more than ten times more than a more recent, higher-powered paper that finds no evidence of gender bias [@RN4801]. Instead of grappling with this bias in a way that attempts to minimise or deny it, researchers would benefit from acknowledging it and centring it in the research process.

Practically, positionality statements, again, provide a framework for acknowledging biases and researcher viewpoints. At this stage of the research process, there may also be scope to embed reflexivity into the research peer review process, ideally, a dedicated ‘section’ expanding on that. As an extreme example of researchers ‘laying bare’ the research process, the Red Team Challenge offered researchers a financially motivated opportunity of a team scouring their materials, data, and code of a submission-ready manuscript, in attempt to catch errors and improve the robustness of the research. A more palatable offer may be a reflexive engagement with who researchers elect to review their manuscripts at the journal submission stage. Again, acknowledgement of biases, conflicting interests, and competing agendas may well be at play during this stage, and this could be ‘spotted’ via reflexive engagement with the research process.

## Broader Engagement and *"Why"*?

This discussion around practical steps that researchers may engage with to embed reflexivity into their work grew out of this project and examining personal lived experience. There are much wider, more epistemological, ontological questions surrounding data usage, ethical considerations, and research frameworks that should also be acknowledged. From this work a primer was developed alongside other researchers in similar positions [@RN2410]. This sets out practical and concrete questions to follow at each step of the research process (see Appendix C). This does not cover a complete adoption of a wholly reflexive approach to research but does provide a starting point in the process. The inclusion of short autoethnographic, reflexive pieces, where I locate myself – as someone with lived experience – in relation to the literature, the process of conducting research, and the data is trying to meet this criteria.

Methodologically, this is probably seen as a somewhat strange addition to a quantitative research project, and may raise questions on why I have chosen to include this information that blurs the boundaries between the public and private spheres where this project sits. Throughout this thesis, I have included pieces that illustrate my personal relationship to the question and context of severe mental illness and employment. The decision to include my experiences within this thesis was a political one, I identify as an intersectional feminist, and also as someone with lived experience of psychosis, cPTSD, and the myriad other changes in labels and social context as is illustrated throughout the pieces. I strongly identified with the individuals in the data from the beginning of this project, as my first severe mental illness diagnosis came two months before beginning this project, and whilst not the same, much of what I experienced was also experienced by the individuals in the data. As explored in this chapter, my disclosure of my own personal context was brought into this project to illustrate my stance, my relationship to the topic, and why I am here. I consider this to be a key strength of this research – both in the generation of theoretical knowledge, and of advancing open, intersectional feminist methodology in relation to how we work with quantitative data. In doing this, the traditional boundaries of a quantitative researcher have been blurred. This is not to detract from the quantitative methods themselves, but to add something more, which I also touch on in Chapter \@ref(chapter8). 

## Summary

In this chapter, a rationale for quantitative research to adopt a similar level of thoughtful reflexivity that is present in qualitative methodologies is presented, and why it is included in this quantitative based thesis. Generally, there are two choices: 1. researcher bias is acknowledged, centered, and celebrated in quantitative work, or 2. researcher bias is deemed to be problematic and is confronted and challenged. Both of these approaches are much more useful than the assumption that such biases do not exist. However, they do represent two very different epistemological approaches. The traditional positivists may prefer the latter of these approaches and relish any opportunity to reduce bias in quantitative research. While this is acceptable and welcomed, encouraging researchers to undertake the messy task of grappling with centring, rather than fighting, biases as quantitative researchers should be encouraged in future. It should also be noted that these should not be considered superficial ‘add ons’ to the research process. Indeed, there some concerns with some existing tools to reform the methodology, because some may simply allow researchers the opportunity to falsely signal or perform ‘bias checking’ in a superficial way. In sum, embedding reflexivity into all research can not only improve the credibility and rigour of research but also fundamentally acknowledge that biases and subjectivities do, in fact, exist.
