---
output:
    thesisdown::thesis_pdf: default
bibliography: bib/thesis.bib
csl: csl/harvard.csl
space_betwee_paragraphs: true
fig_caption: true
always_allow_html: yes
link-citations: true
toc-depth: 3
lot: true
lof: true
editor_options: 
  chunk_output_type: console
---
# Discussion {#chapter7}

## Chapter Overview

This chapter discusses key findings from this thesis and places their implications in context. A section comparing findings to previous research is then presented before a section outlining the general strengths and limitations of the thesis. The final section outlines recommendations for future research. Concluding statements can be found in Chapter \@ref(chapter8).

## Findings in Context 

This section summarises the key findings, relates them to existing literature and draws out implications for policy. There are four subsections covering: 1. The role of demographic factors in economic activity, 2. the impact of common mental health disorders and severe mental illness on economic activity, 3. the effect of treatment use on economic activity, and 4. the influence of common mental health disorders and severe mental illness type on economic activity. 

This work highlights the significant impact that demographic factors, particularly age, gender, and education, have on economic activity in England, particularly in the context of poor mental health. The findings suggest that older individuals and women are more likely to face barriers to employment, and that education has a positive impact on economic activity. To address these issues, it is crucial for society to invest in holistic policies and programs that support individuals with mental illnesses in finding and keeping employment if able, addressing the barriers faced by older individuals and women, and providing support and resources that are tailored to their specific needs. Additionally, it is important to invest in education and training programs that support individuals in gaining the skills and qualifications needed to access employment opportunities, and to address the broader social context, including the prevalence of mental health conditions, the type and source of support and resources, and the level of stigma and discrimination faced by individuals living with mental illnesses.

### Demographic Factors and Economic Activity

The impact of demographic factors on economic activity is a topic that has been widely researched in recent years, particularly in relation to poor mental health and employment. In the UK, the relationship between demographic factors and economic activity is shaped by various social, economic, and political factors, including changes in the labour market, the prevalence of certain mental health conditions, and the availability of support and resources for individuals with common mental health disorders or severe mental illness in particular [@RN2247]. 

The data from the 2000 and 2007 waves of the Adult Psychiatric Morbidity Survey (APMS) suggests that demographic factors such as age, gender, and education have a significant impact on economic activity in England. Individuals aged 55 to 74 were less likely to be economically active, with a negative probability of activity in the 2000 and 2007 survey wave. Similarly, being female was also negatively associated with economic activity in both survey waves. The work by Ralston and Formby [@RN4822] also highlights the significant changes in the occupational position of young people in the UK following the Great Recession. These changes in occupational position, particularly the disproportionate loss of less advantaged occupations for young men and more advantaged occupations for young women, have important implications for mental health outcomes. As research has shown, socioeconomic disadvantage, including unemployment and low income, is associated with poorer mental health outcomes, these shifts in occupational position may be contributing to increased mental health disparities and inequality in the UK, highlighting the need for policies and programs to support young people in finding and maintaining employment.

These findings align with previous research which has demonstrated that older individuals and women are more likely to face different choices and barriers to employment, particularly when they are living with poor mental health. For example, a study by the Royal College of Psychiatrists [@RN371] found that older individuals with mental health conditions are more likely to experience discrimination in the workplace and face barriers to returning to work after a period of absence. Similarly, research by the TUC has shown that women with mental health conditions are more likely to experience discrimination in the workplace and face barriers to progression and career development.

On the other hand, the current work found that education was positively associated with economic activity, with those who have gained a degree the most likely to be economically active. Similarly, those with GCSEs or A Levels also had a positive effect on economic activity, a second to having gained a degree. This is in line with research by the Centre for Mental Health [@RN2349] which found that individuals with higher levels of education are more likely to be economically active and to have better employment outcomes. Furthermore, research by the Mental Health Foundation [@RN2375] found that individuals with higher levels of education are more likely to have better mental health outcomes and less likely to experience discrimination in the workplace.

It is important to note that the relationship between demographic factors and economic activity is complex and shaped by a number of social, cultural, economic, and political factors [@RN2246]. For instance, changes in the labour market and the availability of support and resources for individuals with mental illnesses can impact the relationship between different demographic factors and economic activity. Furthermore, the relationship between demographic factors and economic activity is also shaped by the broader social context, including the prevalence of mental health conditions, the type and source of support and resources, and the level of stigma and discrimination faced by individuals living with mental illnesses.

Overall, the data analysed in this work highlights the significant impact that demographic factors have on economic activity in England, particularly in the context of poor mental health. The findings suggest that older individuals and women are more likely to face barriers to employment and that education has a positive impact on economic activity. These findings show that it is crucial for society to invest in holistic policies and programs that support individuals with mental illnesses in finding and keeping employment if able to. This includes addressing the barriers faced by older individuals and women and providing support and resources that are tailored to their specific needs [@RN208]. Additionally, it is important to invest in education and training programs that support individuals in gaining the skills and qualifications needed to access employment opportunities [@RN4734]. Furthermore, addressing the social determinants of mental health such as poverty, housing, and discrimination will play a crucial role in improving the economic activity of individuals living with common mental health disorders and severe mental illness long term [@RN2236].

To give one example, the Westminster government implemented the New Deal for Disabled People in 2001, which aimed to support individuals with disabilities in finding and maintaining employment. Additionally, the introduction of the Disability Discrimination Act, implemented in 1995, aimed to prevent discrimination against individuals with disabilities in the workplace. These policies were in place during the time period in which the data from the APMS was collected and would have likely had an impact on the relationship between the demographic factors and economic activity. Furthermore, it is also important to consider the broader social and economic context of the time, such as changes in the labour market and the availability of support and resources for individuals with mental illnesses. 

One specific example of a policy response that was implemented between 2000 and 2007 that aimed to address the barriers faced by older women in the workforce was the "Women and Work Commission" established in 2006. The Commission aimed to address the issues faced by women in the workplace, including discrimination, lack of flexible working options, and the gender pay gap. The Commission also focused on addressing the specific challenges faced by older women, such as age discrimination and lack of opportunities for career development. One of the key recommendations from the Commission was to increase the availability of flexible working options for older women, in order to enable them to continue working while balancing care giving responsibilities. Additionally, the Commission recommended initiatives to tackle age discrimination in the workplace and increase opportunities for older women to access training and development programs. This policy aimed to improve the economic activity of older women in the UK, by addressing the barriers they faced in the workforce.

### The Impact of Common Mental Health Disorders and Severe Mental Illness on Economic Activity 

We explored the relationship between common mental health disorders and severe mental illness, and economic activity using data from the two survey waves. The social context of the UK between 2000 and 2007 was marked by a shift towards a more flexible labour market, where individuals with common mental health disorders and severe mental illness may have been at a disadvantage in terms of finding and maintaining employment.

As expected, the results indicate that having a common mental health disorders or severe mental illness was negatively associated with employment and that this association was statistically significant in both survey waves. The negative effect of common mental health disorders on economic activity was found to be stronger in the 2007 survey wave. This negative association between common mental health disorders and severe mental illness and economic activity is consistent with previous research, which has shown that individuals with mental health conditions are more likely to experience economic inactivity, unemployment, and reduced income [@RN4812]. This is particularly concerning given that poverty and social exclusion are known risk factors for mental health problems since it creates the risk of a downward spiral where mental health problems lead to a reduction in income which in turn increases the risk of such problems.

It is important to note that the negative association between common mental health disorders and severe mental illness and economic activity may be influenced by a number of factors, including the availability of treatment and support, the attitudes of employers and colleagues, and the nature of the work itself. For example, research has shown that individuals with common mental health disorders and severe mental illness are more likely to experience discrimination and stigma in the workplace [@RN441]. This can make it difficult for them to find and maintain employment, even when they have the necessary qualifications and skills [@RN2252].

These findings show the need for support for individuals with common mental health disorders and severe mental illness in finding and maintaining employment [@RN2236]. This includes not just providing access to treatment and support, but also addressing the structural and societal factors that contribute to the marginalization and disadvantage of individuals with mental health conditions. One key area is in reducing poverty and social exclusion, as these factors have been shown to have a significant impact on mental health outcomes and can exacerbate the challenges faced by individuals with common mental health disorders and severe mental illness in the workforce. Additionally, promoting positive attitudes towards mental health in the workplace and creating more inclusive and flexible working environments can help to address the discrimination and stigmatization that individuals with mental health conditions often face [@RN4734].

It is also important to note that these findings may be influenced by changes in the prevalence of these conditions within the population and changes in the way that they are diagnosed and treated. However, it is clear that there is a need for further research to better understand the specific challenges faced by individuals with common mental health disorders and severe mental illness in the workplace, as well as the most effective strategies for supporting them, given the significant impact that common mental health disorders and severe mental illness can have on an individual’s ability to participate in the workforce. Furthermore, it is important to recognize that mental health is a social determinant of health and should be addressed holistically by addressing the societal and structural factors that contribute to mental health disparities.

### Effects of Treatment and Service Use on Economic Activity

The effects of treatment or service use on economic activity are a key consideration when examining the relationship between mental health and employment. We may hope that effective treatment or services might increase the changes of those with common mental health disorders or severe mental illness finding or remaining in employment. In practice, the results indicate that treatment and service use are negatively associated with economic activity and indicate illness severity. These findings are consistent with previous research, which suggests that individuals with mental health conditions who receive treatment are more likely to be unemployed or inactive [@RN175]. These results should not be interpreted as indicating that treatments or services are not effective. Rather they indicate that those receiving treatments or using services are likely to experience more severe mental health challenges. To judge the impacts or benefits of treatments and services, we would need a different research design. 

When we control treatment and service use, we still see significant negative relationships between common mental health disorders and severe mental illness, and economic activity. This suggests that even the ‘less unwell’ with these conditions still suffer significant disadvantage in the labour market.  This is a crucial insight, as it highlights the need for wider access to treatment and support services for individuals with common mental health disorders and severe mental illness, even those who are considered to be *"less unwell"*. It suggests that even those who do not currently receive these kinds of services still face significant disadvantages in the labour market. This highlights the importance of addressing the root causes of these conditions, rather than simply treating the symptoms. Additionally, it emphasizes the need for more comprehensive support services that can help individuals with common mental health disorders and severe mental illness to manage their symptoms and maintain employment. This may include mental health services, job training and placement programs, and other social support services that can help to reduce the negative impact of these conditions on economic activity [@RN2235].

However, the results also showed that the using counselling services alone on employment was not statistically associated with lower economic activity in the 2007 survey wave. The lack of a significant relationship between counselling and economic activity suggests that counselling is the treatment that individuals who are least unwell tend to use. This highlights the need for more tailored treatment and support services that can effectively address the specific needs of individuals with common mental health disorders and severe mental illness, regardless of their level of illness. It also suggests that more research is needed to better understand the underlying causes of these conditions and how they impact economic activity. 

Individuals with personality disorders, such as borderline personality disorder, may struggle with managing their emotions and behaviours in a workplace setting. Counselling services may be able to address these issues but may not be able to provide the additional support and accommodation that these individuals may need in order to be successful in a work environment. Research has shown that individuals with severe mental illnesses often have multiple, complex needs that require a coordinated, multidisciplinary approach to treatment and support. This may include not just counselling services, but also employment support, housing support, and other services [@RN175]. Limited access to counselling services in the community and lack of continuity of care may also be a barrier for individuals with severe mental illnesses in finding and maintaining employment. A lack of employment support services specifically tailored to individuals with severe mental illnesses may also play a role in the limited effectiveness of counselling services alone in supporting employment [@RN2254].

This highlights the intersectionality of gender and mental health in determining employment outcomes and the need for gender-sensitive policies and programs to support individuals with mental health conditions in finding and maintaining employment [@RN2369]. This includes developing and implementing gender-sensitive mental health services, such as specialized counselling and support groups, targeted job training and placement services for women with mental health conditions to increase their employability and job retention. Offering flexible work arrangements, such as part-time or telecommuting options to accommodate their needs and support their recovery. Offering accommodation in the workplace, such as mental health days and mental health leave are initiatives that could also impact positively keeping people with common mental health disorders and severe mental illness in employment. Providing education and awareness campaigns for employers should also positively impact,  increasing understanding of mental health conditions and reducing the discrimination and stigma experienced by those living with mental health conditions in the workplace. Offering inclusive parenting support services for caregivers with mental health conditions, such as counselling, support groups, and respite care, to help them manage their condition and continue to provide for their children [@RN2321].

Moreover, the results of this study indicate that the negative effect of common mental health disorders and severe mental illness on economic activity is statistically significant in both survey waves. This is further evidence that individuals with mental health conditions face significant barriers in finding and maintaining employment. These findings have important implications and highlight the need for policies and programs that address the social determinants of mental health, such as poverty and unemployment, and support individuals with mental health conditions in finding and maintaining employment. This includes providing access to comprehensive, evidence-based treatment, including counselling and medication, as well as employment support services, such as job coaching and vocational rehabilitation [@RN4746].

Additionally, the results also highlight the need for policies and programs that address the intersectionality of mental health, gender and socioeconomic status, and support individuals with mental health conditions in navigating the changes in the labour market and finding and maintaining employment. This includes addressing the structural barriers that individuals with mental health conditions face in finding and maintaining employment, such as discrimination and stigma, and providing targeted support for marginalized groups, such as women and ethnic minorities [@RN3434].

### The Influence of Common Mental Health Disorders and Severe Mental Illness Type on Economic Activity

In this section, we explored the influence of specific types of common mental disorders  and severe mental illnesses  on economic activity between 2000 and 2007. Using logistic regression models, we analysed the odds of being economically active while controlling for demographic, health, and educational factors.
One of the key findings in this section was the negative association between specific types of common mental health disorders and economic activity. Results showed that all types of common mental health disorders were associated with a decreased likelihood of being economically active, with depression, generalised anxiety and depression, and mixed anxiety and depression being statistically significant in the 2000 survey. These findings align with previous research that has found individuals with depression to be at an increased risk of inactivity and unemployment [@RN4813]. 

Studies have found that individuals with depression have an increased risk of inactivity and unemployment [@RN4813]. They may have difficulty with motivation, concentration, and energy levels, which can make it hard to carry out daily tasks. They may also experience social withdrawal and isolation, which can further affect their ability to work. Anxiety disorders, such as generalised anxiety disorder (GAD) and social anxiety disorder (SAD), are associated with increased risk of unemployment and reduced productivity at work [@RN4814]. Individuals with GAD may have difficulty with excessive worrying, which can affect their ability to focus and make decisions, while individuals with SAD may have difficulty interacting with others and may avoid social situations, which can make it hard to hold down a job. Individuals with OCD may have difficulty with work performance and career progression due to the time-consuming nature of their compulsions, which can make it hard to meet job demands [@RN4815]. They may also experience social isolation and difficulty forming relationships, which can further affect their ability to work. Studies have found that individuals with panic disorder may have difficulty functioning in the workplace due to the sudden onset of panic attacks and the associated symptoms such as shortness of breath, heart palpitations, and feelings of impending doom [@RN4816]. They may also experience social isolation and difficulty forming relationships, which can further affect their ability to work.

Another key finding was the negative association between specific types of severe mental illness and economic activity. Results showed that both having a psychosis condition or personality disorder were both highly statistically significant and negatively associated with economic activity, with psychosis being more statistically significant than personality disorders in both the 2000 and 2007 survey waves. These findings are consistent with previous studies that have found individuals with psychosis to be at a higher risk of economic inactivity [@RN3505].

These findings on the influence of specific common mental health disorders and severe mental illness types on economic activity are particularly concerning for those individuals living with psychosis and personality disorder. Results show that both having a psychosis condition, or a personality disorder were both highly statistically significant and negatively associated with economic activity, with psychosis being more statistically significant than borderline personality disorder in both the 2000 and 2007 survey waves. This highlights the need for specific and targeted support for individuals living with these conditions in order to promote equality in the workforce and beyond [@RN2236]. 

Individuals living with psychosis may be less likely to be economically active for a variety of reasons, such as symptoms of their condition such as hallucinations, delusions, and disorganized thinking, which can make it difficult for an individual living with the condition to function in a workplace setting. This can lead to increased poverty, stigma, and difficulty functioning within society, which highlights the importance of investing in policies and programs that support individuals with psychosis in finding and keeping employment [@RN4716].

Similarly, individuals living with personality disorder may face challenges in finding and maintaining employment due to their condition. They may face difficulties in managing their emotions and behaviors in a workplace setting, which can lead to discrimination, prejudice, and negative stereotypes. This highlights the need for mental health awareness, education, and inclusion in workplaces, along with providing appropriate treatment and support for individuals living with personality disorders [@RN4736].

This has highlighted the significant difficulties faced by individuals living with common mental health disorders and severe mental illness in the UK in terms of their economic activity. The findings show that specific types of common mental health disorders and severe mental illness, such as depression and psychosis, are associated with a decreased likelihood of being economically active. This is particularly concerning for individuals living with psychosis and personality disorder, who are at a higher risk of economic inactivity and face unique challenges in the workforce. These findings underscore the need for targeted and specific support for individuals living with common mental health disorders and severe mental illness, including addressing societal and structural factors that contribute to mental health disparities and promoting mental health awareness and inclusion in the workplace. It is crucial that society invests in policies and programs that support individuals with common mental health disorders and severe mental illness in finding and keeping employment, in order to promote equality and inclusion for all [@RN2334].

## Comparisons to Previous Research and Contribution

This study is unique in its focus on the specific relationship between common mental disorders and severe mental illnesses and their impact on economic activity. Previous research has primarily examined the effect of mental illness on employment outcomes but has not delved into the specific types of common mental health disorders and severe mental illness that may have a greater impact. It draws on two national cross-sectional surveys of the general population. 

This study found that all types of common mental health disorders were associated with a decreased likelihood of being economically active: with depression; generalised anxiety and depression; and mixed anxiety and depression being statistically significant in the 2000 survey. Additionally, both psychosis conditions and personality disorders were found to be highly statistically significant and negatively associated with economic activity, with psychosis having a greater impact. These findings add to the growing body of literature that highlights the detrimental effect of mental illness on economic activity and the importance of targeted interventions and support for individuals with specific types of common mental health disorders and severe mental illness.

Previous research on the relationship between common mental health disorders and severe mental illness and economic activity has primarily focused on the overall impact of these conditions. This study, however, aimed to specifically examine the influence of specific types of common mental health disorders and severe mental illness on economic activity. The findings of this study support previous research that has shown a negative relationship between common mental health disorders and severe mental illness and economic activity but adds new insight by highlighting the particularly strong negative impact of psychosis and borderline personality disorder on economic activity. These findings contribute to a growing body of research that suggests a need for policies and programs that support individuals with common mental health disorders and severe mental illness in finding and maintaining employment, with a focus on addressing the specific challenges faced by individuals with psychosis and borderline personality disorder. The study used logistic regression models to examine the odds of being employed while controlling for demographic, health, and educational factors.

One key finding of the study is that individuals with common mental health disorders and severe mental illness were less likely to be employed, highlighting the need for better support and policies to help individuals with these conditions find and keep employment. The study also found that treatment use, including the use of mental health services and medication, was negatively associated with employment. Additionally, the study found that specific types of common mental health disorders, such as depression, generalised anxiety and depression, and mixed anxiety and depression, were statistically significant in negatively impacting economic activity.

In comparison to previous research, this study adds to the understanding of the specific challenges faced by individuals with common mental health disorders and severe mental illness in the workplace and the most effective strategies for supporting them. The study also highlights the need for further research to better understand the relationship between specific conditions and economic activity. Additionally, the study's use of data from multiple survey waves and a nationally representative sample allows for a more comprehensive understanding of the relationship between common mental health disorders, severe mental illness and economic activity over time. The study's findings are important for informing policy and practice in the UK and beyond to promote social justice and equality for individuals with common mental health disorders and severe mental illness.

Furthermore, it also examined the impact of specific types of common mental health disorders and severe mental illness on economic activity. The study found that all types of common mental health disorders were associated with a decreased likelihood of being economically active, with depression, generalised anxiety and depression, and mixed anxiety and depression being statistically significant in the 2000 survey. Additionally, the study found that both having a psychosis condition or personality disorder were both highly statistically significant and negatively associated with economic activity, with psychosis being more statistically significant than personality disorders in both the 2000 and 2007 survey waves. These findings are important as they contribute to the understanding of the specific challenges faced by individuals with common mental health disorders and severe mental illness in the workplace and the most effective strategies for supporting them.

This study, which focuses on the relationship between common mental disorders  and severe mental illnesses  and their impact on economic activity, adds to the body of research by using data from two survey waves in 2000 and 2007, applying logistic regression models to determine the odds of being employed while controlling for demographic, health, and educational factors. This allows for a more comprehensive understanding of the relationship between common mental health disorders and severe mental illness and economic activity. Additionally, this study also examines the impact of treatment use on employment outcomes, providing insight into the effectiveness of different forms of treatment in supporting individuals with common mental health disorders and severe mental illness in the workforce. The findings of this study are important as they reveal the significant negative impact that common mental health disorders and severe mental illness can have on an individual's ability to participate in the workforce, highlighting the need for more attention and support for individuals with these conditions in order to promote social justice and equality. This study is also important as it provides a more detailed view of the specific challenges faced by individuals with different types of common mental health disorders and severe mental illness in the workforce, and the most effective strategies for supporting them.

The work adds to the existing body of research on the relationship between common mental disorders and severe mental illnesses  and their impact on economic activity. These findings are important in comparison to previous research, as they provide a comprehensive understanding of the negative impact that common mental health disorders and severe mental illness can have on an individual's ability to participate in the workforce and highlight the need for more attention to be paid to this issue in order to promote social justice and equality in the UK.

The use of logistic regression models in this study to examine the relationship between common mental disorders  and severe mental illnesses  and economic activity, as well as the influence of treatment use on employment outcomes, adds to the growing body of research on the topic. The results of this study, which used data from two survey waves in 2000 and 2007, showed that having a common mental health disorders or severe mental illness was negatively associated with employment and that this association was statistically significant in both survey waves. The negative effect of common mental health disorders on economic activity was found to be stronger in the 2007 survey wave. Additionally, treatment use, including the use of mental health services and medication, was negatively associated with employment. These findings provide important insights into the challenges faced by individuals with common mental health disorders and severe mental illness in the workforce and the potential strategies for supporting them.

It is worth noting that previous research on the impact of common mental disorders  and severe mental illnesses  on economic activity has used a variety of methodologies. For example, some studies have used data from the Adult Psychiatric Morbidity Survey (APMS) to examine the relationship between mental health and employment, while others have used data from other sources. Despite these differences, the findings of this study are consistent with those of previous research in showing that individuals with common mental health disorders and severe mental illness are less likely to be economically active than those without these conditions. Additionally, the use of logistic regression models in this study allows for a more detailed examination of the relationship between mental health and employment, controlling for demographic, health, and educational factors. These findings are important as they highlight the need for better support and policies for individuals with common mental health disorders and severe mental illness in the workforce.

Overall, this study contributes to a growing body of literature that highlights the detrimental effect of mental illness on economic activity and the importance of targeted interventions and support for individuals with specific types of common mental health disorders and severe mental illness. It builds on previous research by specifically examining the influence of different types of common mental health disorders and severe mental illness on economic activity, rather than simply focusing on the overall impact of these conditions. The study's use of data from multiple survey waves and a nationally representative sample allows for a more comprehensive understanding of the relationship between common mental health disorders, severe mental illness and economic activity over time.

One key finding of the study is that individuals with common mental health disorders and severe mental illness were less likely to be employed, highlighting the need for better support and policies to help individuals with these conditions find and keep employment. The study also found that treatment use, including the use of mental health services and medication, was negatively associated with employment. Additionally, the study found that specific types of common mental health disorders, such as depression, generalised anxiety and depression, and mixed anxiety and depression, were statistically significant in negatively impacting economic activity.

The study's findings are important for informing policy and practice in the UK and beyond to promote social justice and equality for individuals, particularly those experiencing multiple and place-based disadvantages associated with decades of de-industrialisation and the degradation of working-class employment opportunities. The belief in the concepts of generations and cultures of worklessness as improperly held and it is time they are done away with [@RN4820]. This will help to dispel the myths and stereotypes that have been used to demonise individuals, particularly those with severe mental illness, and instead focus on addressing the root causes of poverty and inequality. This works results suggest that there is a need for policies and programs that support individuals with common mental health disorders and severe mental illness in finding and maintaining employment, with a focus on addressing the specific challenges faced by individuals with psychosis and borderline personality disorder.

Ralston’s and collegues 2022 findings on the long-term impact of NEET status and the gendering of its outcomes highlights the importance of addressing the root causes of poverty and inequality for young people and emphasizes the gendered nature of work and labour from an early age that can follow into later life. It is clear that policies and programs need to be developed that support individuals, particularly those with severe mental illness, in finding and maintaining employment, to ensure that they have the opportunity to reach their full potential and participate fully in society [@RN4821].

Furthermore, the study emphasizes the need for further research to better understand the relationship specific conditions and economic activity, in order to develop effective interventions and support programs for individuals with common mental health disorders and severe mental illness.

## Strengths and Limitations of This Work

### Strengths 

The study utilizing the APMS data from 2000 and 2007 has several strengths that set it apart from other research that has used this same data. One strength of the study is its use of logistic regression models to determine the odds of being employed while controlling for demographic, health, and educational factors. This allows for a more accurate understanding of the specific relationship between common mental health disorders and severe mental illness and economic activity. Another strength is the use of data from two survey waves, in 2000 and 2007, which allows for an examination of the changes in the relationship between common mental health disorders and severe mental illness and economic activity over time. This allows for a more comprehensive understanding of how these factors have changed and how they may continue to change in the future.

Additionally, the study has a focus on treatment use and its effect on employment outcomes, which is an important aspect that has not been fully explored in previous research. We take treatment used to indicate more severe levels of mental ill health, enabling us to see how the ‘least unwell’ do in the labour market. This highlights the need for further research and support in this area to help all individuals with common mental health disorders and severe mental illness find and maintain employment.

Furthermore, the study's use of a large and nationally representative sample allows for greater generalizability of its findings. In contrast, other studies that have used data from the APMS, such as those conducted by others may have had smaller sample sizes and did not consider, to the same extent, social context in their analysis. Overall, this study builds on previous research by providing a more detailed and nuanced understanding of the relationship between common mental health disorders and severe mental illness and economic activity in the UK.

Finally, the study also considers the social context of the UK between 2000 and 2007, which is an important consideration in understanding the specific challenges faced by individuals with common mental health disorders and severe mental illness in the workforce and how to promote social justice and equality in this area. Overall, the study provides valuable insights and adds to the body of research on common mental health disorders, severe mental illness, and economic activity, and its strengths, such as its critical social justice perspective and consideration of the social context of the UK, set it apart from other studies that have used data from the APMS. The detailed analysis and examination of specific conditions and demographic factors also adds a level of nuance and complexity to the understanding of the relationship between common mental health disorders, severe mental illness, and economic activity. Overall, this study makes an important contribution to the field and its findings should be taken into consideration in future research and policy decisions related to common mental health disorders, severe mental illness, and economic activity.

### Limitations

The study used data from the Adult Psychiatric Morbidity Survey (APMS) to explore the relationship between common mental disorders and severe mental illness and economic activity in England between 2000 and 2007, has several limitations that should be considered when interpreting the results.

First, the study is limited by the cross-sectional design of the APMS, which does not allow for causality to be established. The study is only able to establish associations between common mental health disorders, severe mental illness and economic activity, and not the direction or mechanisms of these associations. Furthermore, the study is based on self-reported data, which may be subject to recall bias and social desirability bias.

Second, the study is limited by the measures used to assess common mental health disorders and severe mental illness and economic activity. The study used the Clinical Interview Schedule-Revised (CIS-R) to assess common mental health disorders and the Schedules for Clinical Assessment in Neuropsychiatry (SCAN) to assess severe mental illness. These measures have been validated for research purposes but may not capture the full range of symptoms and functional impairment associated with common mental health disorders and severe mental illness. Similarly, the study's measure of economic activity, which relied on self-reported employment status, may not properly capture other aspects of economic well-being, such as income and wealth.

Third, the study is limited by the sample used in the analysis. The study excluded individuals who were institutionalized, which could have led to an underestimation of the true prevalence of common mental health disorders and severe mental illness among these groups and the impact of these conditions on economic activity, especially when greater treatment use seems to indicate worse economic outcomes. The study also excluded individuals who were unable to speak English, which could have led to a bias in the sample. The survey also only recorded gender in a traditional binary, (named `sex` in the data, only recorded male and female) and fails to record non-binary or trans-identifying individuals. However, there is growing consensus that this has not stopped trans and non-binary individuals from appearing in survey data, only that previous methods have not captured this group adequately [@RN4817; @RN4818; @RN4819]. 

Fourth, the study is limited by the lack of information on the specific types of common mental health disorders and severe mental illness, which may have different associations with economic activity. The study's focus on common mental health disorders and severe mental illness as broad categories may not capture the heterogeneity within these groups, which could have influenced the results.

One of the main limitations of this study is the small sample size of individuals reporting severe mental illness in both the 2000 and 2007 waves of the APMS. With only 46 and 56 individuals respectively, it is difficult to draw conclusions about the overall population of individuals with severe mental illness in relation to economic activity. The small sample size may lead to issues of sampling bias and limited statistical power, making it difficult to detect true relationships between severe mental illness and economic activity. Additionally, the small sample size may limit the generalizability of the study findings, as it may not accurately represent the experiences of individuals with severe mental illness in the broader population. 

Furthermore, small sample size can also make it difficult to control confounding variables and ensure the robustness of the statistical analyses. Therefore, it is important to interpret the findings of this study with caution and to consider the limitations of the sample size when interpreting the results. It would be beneficial for future research to include a larger sample of individuals reporting severe mental illness to increase the generalizability of the findings. It is worth noting that the small sample size of this study may limit the generalizability of the findings to the wider population. This is a limitation that is consistent with other studies that have used data from the APMS, such as those conducted by previous research that used the data. These studies also had small sample sizes, which limited their ability to make generalizable conclusions about the population as a whole. Additionally, the small sample size in this study increases the likelihood of sampling error, which can lead to inaccurate or unreliable results. It is worth reflecting that the original plan of using administrative data may have overcome this limitation, and the barriers to using administrative data were beyond my control. 
Moreover, the small sample size of this study can be a limitation when it comes to the ability to detect meaningful differences in the data. With a small sample size, any differences found in the data may not be statistically significant and may not be generalizable to the population as a whole. Furthermore, the small sample size of the severe mental illness group (46 and 56 in 2000 and 2007 respectively) specifically, may limit the ability to make conclusions about the specific population of individuals with severe mental illness. This is an important consideration given that the study aims to investigate the effect of common mental health disorders and severe mental illness on economic activity.

It is important to note that while the small sample size is a limitation of this study, it is a limitation that is common among studies that use data from the APMS. This is due to the nature of the survey, which is conducted on a representative sample of the population, rather than a comprehensive sample of the population. This means that while the sample size is small, it is still representative of the population as a whole. However, the small sample size should be considered when interpreting the results of this study and generalizing about the population.

Finally, the study is limited by the social context in which it was conducted. The study's data was collected between 2000 and 2007, which was a period of significant economic and political change in the UK, which could have influenced the results. The data itself cannot consider these changes and their potential impact on the relationship between common mental health disorders and severe mental illness and economic activity. It would also have improved the study to have had access to the APMS data for 2014. As well as providing a third wave of data, this would have extended the study period considerably, bringing in a time when the labour market suffered a significant deterioration after the Global Financial Crisis. However, the 2014 dataset of the APMS is still under a Special License Access agreement and could not be accessed in time to include it in this thesis. 

In conclusion, the work provides important insights into the relationship between common mental health disorders and severe mental illness and economic activity in England between 2000 and 2007. However, the limitations of this works’ methodology and sample must be considered when interpreting the results. These limitations highlight the need for further research to better understand the specific challenges faced by individuals living with common mental health disorders and severe mental illness in the workforce, and to explore the most effective strategies for supporting them. Given the significant impact that common mental health disorders and severe mental illness can have on an individual’s ability to participate in the workforce, it is crucial that more attention is paid to this issue in order to promote social justice and equality in the UK and beyond.

## Recommendations for Future Research

Based on the findings of this work, which used data from the Adult Psychiatric Morbidity Survey (APMS) to examine the relationship between common mental disorders, serious mental illness, and economic activity in England between 2000 and 2007, there are several key recommendations for future research in this area.

Firstly, it is recommended that future studies continue to use a critical social justice perspective when examining the relationship between common mental health disorders, severe mental illness, and economic activity. This study's focus on the social context of the UK between 2000 and 2007 is an important aspect that sets it apart from other studies and highlights the need to consider the broader social and structural factors that impact individuals with common mental health disorders and severe mental illness in the workforce.

Secondly, it is recommended that future studies find ways to access longitudinal data to examine changes in the relationship between common mental health disorders, severe mental illness, and economic activity over time. This study's use of data from two survey waves in 2000 and 2007 allows for some understanding of how these factors have changed and how they may continue to change in the future, but it is limited to not being able to track the same individuals over time. There may be scope to use linked administrative data to achieve this. This could also provide access to substantially greater sample sizes which could increase the level of detail which could be explored in the model. Future studies certainly need to consider using more robust data sources to increase sample size and generalizability of findings. The small sample size of 46 and 56 people reporting severe mental illness in 2000 and 2007, is a limitation of this study, and future studies should consider using more robust data sources to increase sample size and generalizability of findings.

Thirdly, it is recommended that future studies focus on specific types of common mental health disorders and severe mental illness to provide a more nuanced understanding of the relationship between mental health and economic activity. This study's focus on specific types of common mental health disorders and severe mental illness allows for a more accurate understanding of the specific challenges faced by individuals with different mental health conditions in the workforce.

Fourthly, it is recommended that future studies consider the use of mental health services and medication as a predictor of employment outcomes. This study's focus on the treatment use and its effect on employment outcomes is an important aspect that has not been fully explored in previous research and highlights the need for further research and support in this area to help individuals with common mental health disorders and severe mental illness find and maintain employment.

In addition to the recommendations for future research that have been previously discussed, there are several other areas that should be explored in order to further our understanding of the relationship between common mental health disorders, severe mental illness, and economic activity. One key area for future research is to examine the specific barriers and facilitators to employment for individuals with common mental health disorders and severe mental illness. This could include looking at the role of stigma and discrimination, as well as the impact of individual, organizational, and societal level factors on employment outcomes. Furthermore, research should also focus on understanding the role of different types of treatment and support in promoting employment for individuals with common mental health disorders and severe mental illness.

Another major area for future research is to examine the relationship between common mental health disorders, severe mental illness, and economic activity in other countries and cultural contexts. This would allow for a more comprehensive understanding of the global impact of common mental health disorders and severe mental illness on economic activity and would also provide valuable information for the development of cross-cultural policies and interventions. Additionally, future research should also examine the relationship between common mental health disorders, severe mental illness, and economic activity in different age groups and across the lifespan.

Finally, it is also important to consider the intersectionality of different demographic factors and how they may impact the relationship between common mental health disorders, severe mental illness, and economic activity. For example, research should examine the impact of race, ethnicity, and socioeconomic status on the relationship between common mental health disorders, severe mental illness, and economic activity, as well as the role of gender and gender identity, with more attention being paid to how we can accurately capture trans and non-binary individuals for example [@RN4819] whether or not they already participate in survey data. By considering these intersectional factors, we can gain a more comprehensive understanding of the unique challenges faced by different groups of individuals with common mental health disorders and severe mental illness and how to promote social justice and equality in this area.

Overall, the study has provided valuable insights into the relationship between common mental health disorders, severe mental illness, and economic activity in England between 2000 and 2007. However, the limitations of the study, such as the small sample size and limited generalizability, must be taken into consideration when interpreting the findings. To build on the research conducted in this study, future research should focus on increasing sample size, incorporating a more diverse population, and utilizing more robust measures of common mental health disorders, severe mental illness, and economic activity. Additionally, future research should consider the role of social and economic policies in impacting the relationship between common mental health disorders, severe mental illness and economic activity, as well as the role of mental health support and treatment on employment outcomes. Furthermore, the research should also be done in other countries to see how the relationship between common mental health disorders, severe mental illness and economic activity varies across different cultures and contexts. By addressing these limitations and building on the strengths of this study, future research can provide a more comprehensive understanding of the relationship between common mental health disorders, severe mental illness, and economic activity, and inform policies and practices that promote social justice and equality for individuals with common mental health disorders and severe mental illness in the workforce.
